(function(){
'use strict';var Xw,sw,Zb,Yi,lp,xp,Fp,Ip,Jp,Kp,pr,qr,pq,qq,rq,sq,lr,tq;Xw=function(a,b){return $APP.vj[a]=b};
sw=function(a,b){a=new $APP.U(null,2,5,$APP.X,[$APP.nq(a),b],null);a=$APP.O(a,0,null);a=$APP.S(a);a=$APP.Gb(a,$APP.Tu);a=$APP.lq(a);b={strokeLinecap:"round",strokeLinejoin:"round",d:"m8.25 4.5 7.5 7.5-7.5 7.5"};b=$APP.Gn.i?$APP.Gn.i("path",b):$APP.Gn.call(null,"path",b);a={xmlns:"http://www.w3.org/2000/svg",fill:"none",viewBox:"0 0 24 24",strokeWidth:1.5,stroke:"currentColor",className:a,children:b};return $APP.Gn.i?$APP.Gn.i("svg",a):$APP.Gn.call(null,"svg",a)};
Zb=function(a,b){if(a!=null&&a.yd!=null)a=a.yd(a,b);else{var c=Zb[$APP.p(a==null?null:a)];if(c!=null)a=c.i?c.i(a,b):c.call(null,a,b);else if(c=Zb._,c!=null)a=c.i?c.i(a,b):c.call(null,a,b);else throw $APP.x("ISet.-disjoin",a);}return a};Yi=function(a){if($APP.ie(a))return(a&1)===0;throw Error(["Argument must be an integer: ",$APP.y.j(a)].join(""));};lp=function(a){return["€",$APP.y.j(a.toLocaleString("en-US"))].join("")};xp=function(a){return $APP.se(Wi,$APP.Kf.i(tw,a))};
Fp=function(a,b){a=new $APP.U(null,2,5,$APP.X,[$APP.nq(a),b],null);a=$APP.O(a,0,null);a=$APP.S(a);a=$APP.Gb(a,uw);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));var c=$APP.se(Wi,$APP.Kf.i(function(d){return xp(vw.j(d))},a));a=function(){return{className:"bg-slate-200 text-slate-900 flex justify-between items-center px-4 py-4 mt-4",children:[function(){var d={className:"font-semibold text-2xl",children:"BUDGET"};d={className:"w-6/12 ",children:$APP.Gn.i?$APP.Gn.i("h3",d):$APP.Gn.call(null,
"h3",d)};return $APP.Gn.i?$APP.Gn.i("div",d):$APP.Gn.call(null,"div",d)}(),function(){var d={className:"w-1/12 "};return $APP.Gn.i?$APP.Gn.i("div",d):$APP.Gn.call(null,"div",d)}(),function(){var d={className:"font-medium ",children:lp(c)};d={className:"w-4/12 flex justify-end items-center space-x-4 ",children:$APP.Gn.i?$APP.Gn.i("span",d):$APP.Gn.call(null,"span",d)};return $APP.Gn.i?$APP.Gn.i("div",d):$APP.Gn.call(null,"div",d)}(),function(){var d={className:"w-1/12"};return $APP.Gn.i?$APP.Gn.i("div",
d):$APP.Gn.call(null,"div",d)}()]}}();return $APP.Hn.i?$APP.Hn.i("li",a):$APP.Hn.call(null,"li",a)};
Ip=function(a,b){a=new $APP.U(null,2,5,$APP.X,[$APP.nq(a),b],null);a=$APP.O(a,0,null);a=$APP.S(a);b=$APP.Gb(a,$APP.Uu);var c=$APP.Gb(a,ww);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));var d=!Yi(b);a=function(){return{className:$APP.lq(["px-4 py-2 flex justify-between items-center ",d?"bg-slate-700/50":""].join("")),children:[function(){var e={children:$APP.$u.j(c)};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),function(){var e={className:"text-slate-300 font-medium",
children:lp(tw.j(c))};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}()]}}();return $APP.Hn.i?$APP.Hn.i("li",a):$APP.Hn.call(null,"li",a)};
Jp=function(a,b){a=new $APP.U(null,2,5,$APP.X,[$APP.nq(a),b],null);a=$APP.O(a,0,null);a=$APP.S(a);b=$APP.Gb(a,$APP.Uu);var c=$APP.Gb(a,xw),d=$APP.Gb(a,yw),e=$APP.Gb(a,zw);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));var f=["item-",$APP.y.j(b)].join(""),h=xp(vw.j(c)),k=!Yi(b);a=function(){return{className:$APP.lq(["overflow-hidden ",k?"":"bg-slate-800"].join("")),children:[function(){var l=function(){return{className:"flex justify-between items-center px-4 py-4 cursor-pointer transition-colors",
onClick:function(){function m(n){return $APP.w(n.j?n.j(f):n.call(null,f))?Wd.i(n,f):$APP.Kd.i(n,f)}return d.j?d.j(m):d.call(null,m)},children:[function(){var m={className:"font-semibold text-2xl",children:$APP.$u.j(c)};m={className:"w-6/12 ",children:$APP.Gn.i?$APP.Gn.i("h3",m):$APP.Gn.call(null,"h3",m)};return $APP.Gn.i?$APP.Gn.i("div",m):$APP.Gn.call(null,"div",m)}(),function(){var m={className:"w-1/12 "};return $APP.Gn.i?$APP.Gn.i("div",m):$APP.Gn.call(null,"div",m)}(),function(){var m={className:"font-medium",
children:lp(h)};m={className:"w-4/12 flex justify-end items-center ",children:$APP.Gn.i?$APP.Gn.i("span",m):$APP.Gn.call(null,"span",m)};return $APP.Gn.i?$APP.Gn.i("div",m):$APP.Gn.call(null,"div",m)}(),function(){var m=$APP.lq(["w-5 h-5 transition-transform ",$APP.w(e.j?e.j(f):e.call(null,f))?"rotate-90":null].join(""));var n={};n=$APP.Gn.i?$APP.Gn.i(sw,n):$APP.Gn.call(null,sw,n);m={className:m,children:n};m={className:"w-1/12 flex justify-end items-center ",children:$APP.Gn.i?$APP.Gn.i("div",m):
$APP.Gn.call(null,"div",m)};return $APP.Gn.i?$APP.Gn.i("div",m):$APP.Gn.call(null,"div",m)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",l):$APP.Hn.call(null,"div",l)}(),$APP.w(e.j?e.j(f):e.call(null,f))?function(){var l=function(){return{className:"text-base bg-slate-900",children:function(){var m=function(){return{className:"pt-2",children:$APP.sg(function(n,q){q={idx:n,detail:q};n=["detail-",$APP.y.j(n)].join("");return $APP.Gn.l?$APP.Gn.l(Ip,q,n):$APP.Gn.call(null,Ip,q,n)},vw.j(c))}}();return $APP.Gn.i?
$APP.Gn.i("ul",m):$APP.Gn.call(null,"ul",m)}()}}();return $APP.Gn.i?$APP.Gn.i("div",l):$APP.Gn.call(null,"div",l)}():null]}}();return $APP.Hn.i?$APP.Hn.i("li",a):$APP.Hn.call(null,"li",a)};
Kp=function(a,b){a=new $APP.U(null,2,5,$APP.X,[$APP.nq(a),b],null);a=$APP.O(a,0,null);a=$APP.S(a);var c=$APP.Gb(a,uw);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));a=$APP.Cp($APP.Lh);var d=$APP.O(a,0,null),e=$APP.O(a,1,null);a=function(){return{className:"w-full text-white",children:[$APP.sg(function(f,h){h={idx:f,item:h,"set-expanded-items":e,"expanded-items":d};f=[$APP.y.j(f),"-section"].join("");return $APP.Gn.l?$APP.Gn.l(Jp,h,f):$APP.Gn.call(null,Jp,h,f)},c),function(){var f=
{"cost-data":c};return $APP.Gn.i?$APP.Gn.i(Fp,f):$APP.Gn.call(null,Fp,f)}()]}}();return $APP.Hn.i?$APP.Hn.i("ol",a):$APP.Hn.call(null,"ol",a)};pr=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return qr(arguments[0],1<b.length?new $APP.cd(b.slice(1),0,null):null)};
qr=function(a,b){b=$APP.S(b);var c=$APP.Pb(b,Aw,.1),d=$APP.Pb(b,Bw,"0px"),e=$APP.Gb(b,$APP.Jd),f=$APP.Gb(b,Cw),h=$APP.Cp(!1);b=$APP.O(h,0,null);var k=$APP.O(h,1,null);h=$APP.Cp(!1);var l=$APP.O(h,0,null),m=$APP.O(h,1,null);h=$APP.Hp(function(){if($APP.w($APP.A(a))){var q=new IntersectionObserver(function(r){r=$APP.F(r);for(var u=null,z=0,G=0;;)if(G<z){var D=u.ea(null,G),K=D.isIntersecting;k.j?k.j(K):k.call(null,K);$APP.w(K)&&(m.j?m.j(!0):m.call(null,!0),$APP.w(e)&&(e.j?e.j(D):e.call(null,D)));$APP.w(function(){var V=
$APP.lb(K);return V?l:V}())&&$APP.w(f)&&(f.j?f.j(D):f.call(null,D));G+=1}else if(r=$APP.F(r)){u=r;if($APP.de(u))r=$APP.Ec(u),z=$APP.Fc(u),u=r,D=$APP.N(r),r=z,z=D;else{D=$APP.H(u);var P=D.isIntersecting;k.j?k.j(P):k.call(null,P);$APP.w(P)&&(m.j?m.j(!0):m.call(null,!0),$APP.w(e)&&(e.j?e.j(D):e.call(null,D)));$APP.w(function(){var V=$APP.lb(P);return V?l:V}())&&$APP.w(f)&&(f.j?f.j(D):f.call(null,D));r=$APP.I(u);u=null;z=0}G=0}else return null},{threshold:c,rootMargin:d});q.observe($APP.A(a));return function(){return q.disconnect()}}return null});
var n=[a,c,d];$APP.Z.i?$APP.Z.i(h,n):$APP.Z.call(null,h,n);return new $APP.U(null,2,5,$APP.X,[l,b],null)};
pq=function(a){$APP.nq(a);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));a=function(){return{className:"flex flex-col justify-center h-full w-full py-8 text-2xl",children:[function(){var b={className:"mb-8 p-4 text-5xl font-futura font-bold",children:"BUDGET"};return $APP.Gn.i?$APP.Gn.i("p",b):$APP.Gn.call(null,"p",b)}(),function(){var b=function(){return{className:"p-4 mb-12",children:function(){var c=function(){return{children:["The total budget for the Armenian Pavilion 2026 is approximately ",
function(){var d={className:"font-bold",children:"1,4M Euro, "};return $APP.Gn.i?$APP.Gn.i("span",d):$APP.Gn.call(null,"span",d)}(),function(){var d={className:"font-bold",children:"1,6M USD"};return $APP.Gn.i?$APP.Gn.i("span",d):$APP.Gn.call(null,"span",d)}(),", covering all aspects of production, installation, operations, marketing, and documentation."]}}();return $APP.Hn.i?$APP.Hn.i("p",c):$APP.Hn.call(null,"p",c)}()}}();return $APP.Gn.i?$APP.Gn.i("div",b):$APP.Gn.call(null,"div",b)}(),function(){var b=
{"cost-data":Lp};return $APP.Gn.i?$APP.Gn.i(Kp,b):$APP.Gn.call(null,Kp,b)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",a):$APP.Hn.call(null,"div",a)};
qq=function(a){$APP.nq(a);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));a=function(){return{children:[function(){var b={src:"images/graphics/biennale_logo.png"};b={className:"w-1/2 lg:w-1/4 lg:max-w-64 mt-4 lg:mt-12 px-4",children:$APP.Gn.i?$APP.Gn.i("img",b):$APP.Gn.call(null,"img",b)};return $APP.Gn.i?$APP.Gn.i("div",b):$APP.Gn.call(null,"div",b)}(),function(){var b=function(){return{className:"text-xl italic text-white px-4 mt-12 mb-8",children:function(){var c=function(){return{children:[function(){var d=
{children:"Armenian Pavilion"};return $APP.Gn.i?$APP.Gn.i("li",d):$APP.Gn.call(null,"li",d)}(),function(){var d={children:"Artist: Zadik Zadikian"};return $APP.Gn.i?$APP.Gn.i("li",d):$APP.Gn.call(null,"li",d)}(),function(){var d={children:"Curator: Tony Shafrazi"};return $APP.Gn.i?$APP.Gn.i("li",d):$APP.Gn.call(null,"li",d)}(),function(){var d={children:"Curator: Tina Chakarian"};return $APP.Gn.i?$APP.Gn.i("li",d):$APP.Gn.call(null,"li",d)}(),function(){var d={children:"2026 Venice Biennale"};return $APP.Gn.i?
$APP.Gn.i("li",d):$APP.Gn.call(null,"li",d)}()]}}();return $APP.Hn.i?$APP.Hn.i("ul",c):$APP.Hn.call(null,"ul",c)}()}}();return $APP.Gn.i?$APP.Gn.i("div",b):$APP.Gn.call(null,"div",b)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",a):$APP.Hn.call(null,"div",a)};
rq=function(a){$APP.nq(a);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));var b=$APP.Zm();a=function(){return{className:"text-white\n                     \n                     flex\n                     justify-center\n                     flex-col\n                     h-full\n                     \n                      w-full\n                     \n                     text-2xl\n                     lg:text-2xl",children:[function(){var c=function(){return{className:"p-4",
children:[function(){var d={className:"\n                          mb-8\n                          font-bold\n                          font-futura\n                          text-5xl",children:"THE STUDIO"};return $APP.Gn.i?$APP.Gn.i("p",d):$APP.Gn.call(null,"p",d)}(),function(){var d=function(){return{className:"leading-relaxed text-lg md:text-xl",children:[function(){var e={className:"font-bold text-pink-400",children:"THE STUDIO "};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",
e)}(),"is conceived as a living, evolving workspace—an active site of fabrication, touch, and continual reconfiguration. Throughout the Biennale, ",function(){var e={className:"font-semibold italic",children:"Zadik Zadikian and his team"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}()," transform the Armenian Pavilion into a functioning studio where plaster units are cast, pigmented, stacked, dismantled, and rebuilt in shifting constellations. ",function(){var e={className:"italic",
children:"This is not a performance or a simulation,"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}()," but the studio made visible: an oasis and natural habitat in which ",function(){var e={className:"font-medium",children:"making itself becomes the work."};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}()]}}();return $APP.Hn.i?$APP.Hn.i("p",d):$APP.Hn.call(null,"p",d)}(),function(){var d=function(){return{className:"mt-6 leading-relaxed text-lg md:text-xl",
children:["At the heart of the project is an ",function(){var e={className:"font-semibold",children:"invented casting process"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),", in which liquid plaster is poured onto flat glass, producing planes of exceptional smoothness reinforced with lightweight foam cores. Pigment is embedded at the moment of formation, saturating each unit from within, while select pieces are ",function(){var e={className:"font-semibold text-yellow-400",
children:"gilded in 24-karat gold"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),", marking moments where the elemental meets the transcendent. These blocks recall ",function(){var e={className:"italic",children:"Armenian tufo"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),"—humble, ancient, and foundational—returning to Zadikian as memory, metaphor, and form, and mirroring the diasporic condition of ",function(){var e={className:"italic",children:"endurance through fragmentation and reinvention."};
return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}()]}}();return $APP.Hn.i?$APP.Hn.i("p",d):$APP.Hn.call(null,"p",d)}(),function(){var d=function(){return{className:"mt-6 leading-relaxed text-lg md:text-xl",children:["Guided by the ethos of ",function(){var e={className:"italic font-medium",children:"In Minor Keys"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),", ",function(){var e={className:"font-bold text-pink-400",children:"THE STUDIO "};return $APP.Gn.i?
$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),"elevates the quiet, easily overlooked unit through care, repetition, and precision. Over seven months, structures are endlessly assembled and disassembled like ",function(){var e={className:"italic",children:"musical modulations"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),", remaining perpetually unfinished. Visitors are invited into this process through touch, making ",function(){var e={className:"font-medium",children:"haptic experience a mode of knowledge and participation."};
return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}()," In this communal space of slowness and attention, ",function(){var e={className:"font-bold",children:"THE STUDIO becomes the artwork itself"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),": a place where making is continuous, form is fluid, and the elemental reveals its quiet, enduring power."]}}();return $APP.Hn.i?$APP.Hn.i("p",d):$APP.Hn.call(null,"p",d)}(),function(){var d={className:"w-12 mt-12 border-t border-pink-500"};
d={className:"flex items-center justify-center",children:$APP.Gn.i?$APP.Gn.i("div",d):$APP.Gn.call(null,"div",d)};return $APP.Gn.i?$APP.Gn.i("div",d):$APP.Gn.call(null,"div",d)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",c):$APP.Hn.call(null,"div",c)}(),function(){var c=function(){return{className:"w-full h-full flex flex-col gap-4 mt-12",children:[function(){var d=$APP.Dp("outer-ctx"),e=pr(d);$APP.O(e,0,null);var f=$APP.O(e,1,null);e=function(){return{className:"",ref:d,children:$APP.w(b)?function(){var h=
{"playback-id":"fuKbU028e02haCGC2i94J15M00lnafQ94p01YgKQ4JPPwfo","should-play?":f,"allow-audio?":!0};return $APP.Gn.i?$APP.Gn.i($APP.fo,h):$APP.Gn.call(null,$APP.fo,h)}():function(){var h={"playback-id":"7qwSp8dt00X2Qht88MC86zyKRc4mykJno5TpkflUuN5E","should-play?":f,"allow-audio?":!1};return $APP.Gn.i?$APP.Gn.i($APP.fo,h):$APP.Gn.call(null,$APP.fo,h)}()}}();return $APP.Gn.i?$APP.Gn.i("div",e):$APP.Gn.call(null,"div",e)}(),function(){var d={"img-src":"https://atd-722658831.imgix.net/simple_blocks/FileName_001Beauty_ViewLayer_099-3.tif",
caption:"BLUE YELLOW BLUE YELLOW",credit:"© Zadik Zadikian 2026"};return $APP.Gn.i?$APP.Gn.i($APP.kp,d):$APP.Gn.call(null,$APP.kp,d)}(),function(){var d={"img-src":"https://atd-722658831.imgix.net/photos/DSC02376%20Large.jpeg",caption:"Stacked units",credit:"Los Angeles, 2025"};return $APP.Gn.i?$APP.Gn.i($APP.kp,d):$APP.Gn.call(null,$APP.kp,d)}(),function(){var d={"img-src":"https://atd-722658831.imgix.net/photos/DSC02363%20Large.jpeg",caption:"Making of blue unit",credit:"Los Angeles, 2025"};return $APP.Gn.i?
$APP.Gn.i($APP.kp,d):$APP.Gn.call(null,$APP.kp,d)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",c):$APP.Hn.call(null,"div",c)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",a):$APP.Hn.call(null,"div",a)};
sq=function(a){$APP.nq(a);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));a=function(){return{children:[function(){var b={className:"mb-8 p-4 text-5xl font-futura font-bold",children:"DONATION INFORMATION"};return $APP.Gn.i?$APP.Gn.i("p",b):$APP.Gn.call(null,"p",b)}(),function(){var b=function(){return{className:"px-4 mb-12 text-lg md:text-xl leading-relaxed text-slate-300",children:[function(){var c=function(){return{children:["The Armenian Pavilion 2026 is supported through ",
function(){var d={className:"font-semibold",children:"Fallen Angels Inc."};return $APP.Gn.i?$APP.Gn.i("span",d):$APP.Gn.call(null,"span",d)}(),", a registered ",function(){var d={className:"font-semibold",children:"501(c)(3)"};return $APP.Gn.i?$APP.Gn.i("span",d):$APP.Gn.call(null,"span",d)}()," non-profit organization. ",function(){var d={className:"font-semibold",children:"Contributions are tax deductible"};return $APP.Gn.i?$APP.Gn.i("span",d):$APP.Gn.call(null,"span",d)}()," to the extent permitted by law."]}}();
return $APP.Hn.i?$APP.Hn.i("p",c):$APP.Hn.call(null,"p",c)}(),function(){var c=function(){return{className:"mt-6 space-y-1",children:[function(){var d={className:"font-semibold",children:"Organization: "};d={children:[$APP.Gn.i?$APP.Gn.i("span",d):$APP.Gn.call(null,"span",d),"Fallen Angels Inc."]};return $APP.Hn.i?$APP.Hn.i("p",d):$APP.Hn.call(null,"p",d)}(),function(){var d=function(){return{children:[function(){var e={className:"font-semibold",children:"EIN: "};return $APP.Gn.i?$APP.Gn.i("span",
e):$APP.Gn.call(null,"span",e)}(),function(){var e={className:"font-bold text-slate-100",children:"92-2395513"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}()]}}();return $APP.Hn.i?$APP.Hn.i("p",d):$APP.Hn.call(null,"p",d)}(),function(){var d=function(){return{children:[function(){var e={className:"font-semibold",children:"Located in: "};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),function(){var e={className:"font-bold text-slate-100",children:"Los Angeles, CA"};
return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}()]}}();return $APP.Hn.i?$APP.Hn.i("p",d):$APP.Hn.call(null,"p",d)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",c):$APP.Hn.call(null,"div",c)}(),function(){var c=function(){return{className:"mt-10 grid grid-cols-1 lg:grid-cols-2 gap-10",children:[function(){var d=function(){return{children:[function(){var e={className:"italic font-normal text-slate-300",children:"Transfers"};e={className:"text-3xl font-futura font-bold text-slate-100 mb-4",
children:["Domestic ",$APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)]};return $APP.Hn.i?$APP.Hn.i("p",e):$APP.Hn.call(null,"p",e)}(),function(){var e=function(){return{className:"space-y-3",children:[function(){var f=function(){return{className:"flex items-baseline justify-between gap-6",children:[function(){var h={className:"font-semibold",children:"Name:"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}(),function(){var h={className:"text-right",children:"Fallen Angels Inc."};
return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",f):$APP.Hn.call(null,"div",f)}(),function(){var f=function(){return{className:"flex items-baseline justify-between gap-6",children:[function(){var h={className:"font-semibold",children:"Routing:"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}(),function(){var h={className:"text-right font-bold text-slate-100 tracking-wide",children:"091311229"};return $APP.Gn.i?$APP.Gn.i("span",
h):$APP.Gn.call(null,"span",h)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",f):$APP.Hn.call(null,"div",f)}(),function(){var f=function(){return{className:"flex items-baseline justify-between gap-6",children:[function(){var h={className:"font-semibold",children:"Account #:"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}(),function(){var h={className:"text-right font-bold text-slate-100 tracking-wide",children:"202535309341"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",
h)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",f):$APP.Hn.call(null,"div",f)}(),function(){var f=function(){return{className:"flex items-start justify-between gap-6",children:[function(){var h={className:"font-semibold",children:"Address:"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}(),function(){var h=function(){return{className:"text-right leading-snug",children:[function(){var k={children:"Choice Financial Group"};return $APP.Gn.i?$APP.Gn.i("p",k):$APP.Gn.call(null,"p",k)}(),
function(){var k={children:"4501 23rd Avenue S"};return $APP.Gn.i?$APP.Gn.i("p",k):$APP.Gn.call(null,"p",k)}(),function(){var k={children:"Fargo, ND 58104"};return $APP.Gn.i?$APP.Gn.i("p",k):$APP.Gn.call(null,"p",k)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",h):$APP.Hn.call(null,"div",h)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",f):$APP.Hn.call(null,"div",f)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",e):$APP.Hn.call(null,"div",e)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",d):$APP.Hn.call(null,"div",d)}(),
function(){var d=function(){return{children:[function(){var e={className:"italic font-normal text-slate-300",children:"Transfers"};e={className:"text-3xl font-futura font-bold text-slate-100 mb-4",children:["International ",$APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)]};return $APP.Hn.i?$APP.Hn.i("p",e):$APP.Hn.call(null,"p",e)}(),function(){var e=function(){return{className:"space-y-3",children:[function(){var f=function(){return{className:"flex items-baseline justify-between gap-6",
children:[function(){var h={className:"font-semibold",children:"Name:"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}(),function(){var h={className:"text-right",children:"Fallen Angels Inc."};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",f):$APP.Hn.call(null,"div",f)}(),function(){var f=function(){return{className:"flex items-baseline justify-between gap-6",children:[function(){var h={className:"font-semibold",children:"SWIFT/BIC:"};
return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}(),function(){var h={className:"text-right font-bold text-slate-100 tracking-wide",children:"CHFGUS44021"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",f):$APP.Hn.call(null,"div",f)}(),function(){var f=function(){return{className:"flex items-baseline justify-between gap-6",children:[function(){var h={className:"font-semibold",children:"ABA/Routing:"};return $APP.Gn.i?$APP.Gn.i("span",
h):$APP.Gn.call(null,"span",h)}(),function(){var h={className:"text-right font-bold text-slate-100 tracking-wide",children:"091311229"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",f):$APP.Hn.call(null,"div",f)}(),function(){var f=function(){return{className:"flex items-baseline justify-between gap-6",children:[function(){var h={className:"font-semibold",children:"IBAN/Account #:"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,
"span",h)}(),function(){var h={className:"text-right font-bold text-slate-100 tracking-wide",children:"202535309341"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",f):$APP.Hn.call(null,"div",f)}(),function(){var f=function(){return{className:"flex items-start justify-between gap-6",children:[function(){var h={className:"font-semibold",children:"Address:"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}(),function(){var h=
function(){return{className:"text-right leading-snug",children:[function(){var k={children:"Choice Financial Group"};return $APP.Gn.i?$APP.Gn.i("p",k):$APP.Gn.call(null,"p",k)}(),function(){var k={children:"4501 23rd Avenue S"};return $APP.Gn.i?$APP.Gn.i("p",k):$APP.Gn.call(null,"p",k)}(),function(){var k={children:"Fargo, ND 58104"};return $APP.Gn.i?$APP.Gn.i("p",k):$APP.Gn.call(null,"p",k)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",h):$APP.Hn.call(null,"div",h)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",
f):$APP.Hn.call(null,"div",f)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",e):$APP.Hn.call(null,"div",e)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",d):$APP.Hn.call(null,"div",d)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",c):$APP.Hn.call(null,"div",c)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",b):$APP.Hn.call(null,"div",b)}(),function(){var b={className:"p-4 mt-10 text-sm md:text-base text-slate-400",children:"If you would like a receipt letter for your records, please include your name and email address with the transfer memo."};
return $APP.Gn.i?$APP.Gn.i("p",b):$APP.Gn.call(null,"p",b)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",a):$APP.Hn.call(null,"div",a)};
lr=function(a){$APP.nq(a);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));a=$APP.Cp(!1);var b=$APP.O(a,0,null),c=$APP.O(a,1,null);a=function(){return{className:"",children:[function(){var d={className:"text-5xl font-futura font-bold",children:"PRESS RELEASE"};d={className:"p-4 mt-12",children:$APP.Gn.i?$APP.Gn.i("p",d):$APP.Gn.call(null,"p",d)};return $APP.Gn.i?$APP.Gn.i("div",d):$APP.Gn.call(null,"div",d)}(),function(){var d=function(){return{children:[function(){var e={className:"p-4 text-3xl font-futura italic",
children:"Nov 15, 2025"};return $APP.Gn.i?$APP.Gn.i("p",e):$APP.Gn.call(null,"p",e)}(),function(){var e=function(){return{className:"px-4 text-lg md:text-xl leading-relaxed text-slate-300",children:[function(){var f={className:"font-bold italic mb-6 text-pink-600",children:"Artist Zadik Zadikian and legendary art dealer Tony Shafrazi to represent Armenia at the 61st Venice Biennale"};return $APP.Gn.i?$APP.Gn.i("p",f):$APP.Gn.call(null,"p",f)}(),function(){var f=function(){return{className:"font-medium mb-6",
children:[function(){var h={className:"italic",children:"Yerevan / Los Angeles / Venice — "};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}(),"The Ministry of Culture of the Republic of Armenia has selected ",function(){var h={className:"font-semibold",children:"Zadik Zadikian"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}()," to represent Armenia at the ",function(){var h={className:"font-semibold",children:"61st Venice Biennale Arte"};return $APP.Gn.i?$APP.Gn.i("span",
h):$APP.Gn.call(null,"span",h)}()," in 2026. Led by legendary art dealer ",function(){var h={className:"font-semibold",children:"Tony Shafrazi"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}()," as Chief Curator, the Pavilion aligns with Armenia's broader commitment to elevating its cultural presence on the international stage."]}}();return $APP.Hn.i?$APP.Hn.i("p",f):$APP.Hn.call(null,"p",f)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",e):$APP.Hn.call(null,"div",e)}()]}}();return $APP.Hn.i?
$APP.Hn.i("div",d):$APP.Hn.call(null,"div",d)}(),$APP.w(b)?function(){var d=function(){return{className:"px-4 text-lg md:text-xl leading-relaxed text-slate-300",children:[function(){var e={className:"mb-6",children:"This collaboration marks a historic and deeply resonant moment in both Zadikian's and Shafrazi's lives and careers: a symbolic return to Armenia and a shared mission to present a world-class national Pavilion to a global audience."};return $APP.Gn.i?$APP.Gn.i("p",e):$APP.Gn.call(null,
"p",e)}(),function(){var e=function(){return{className:"mb-6",children:["Zadikian—who left Soviet Armenia at nineteen and experienced a radical cultural rupture upon arriving in the United States—came of age artistically through an uncommon trajectory. From San Francisco during the height of the countercultural moment, working with ",function(){var f={className:"italic",children:"Benjamin Bufano"};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}(),", to New York, where he assisted ",
function(){var f={className:"italic",children:"Richard Serra"};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}()," on monumental oil-stick wall drawings—one of which Serra titled ",function(){var f={className:"italic",children:"Zadikian"};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}(),"—the artist now returns with a project of uncommon ambition and conceptual rigor."]}}();return $APP.Hn.i?$APP.Hn.i("p",e):$APP.Hn.call(null,"p",e)}(),function(){var e={className:"font-bold text-pink-400",
children:"THE STUDIO "};e={className:"mb-6",children:[$APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e),"transforms the Armenian Pavilion into an active site of sustained, concentrated making. Throughout the Biennale, Zadikian and his team will fabricate primordial plaster units on site—ranging from palm-sized objects to human-scale forms—each one a three-dimensional articulation of distilled color, ratio, and reflectivity."]};return $APP.Hn.i?$APP.Hn.i("p",e):$APP.Hn.call(null,"p",e)}(),
function(){var e={className:"mb-6 italic",children:'" We\'re creating material that transforms by its very nature into sculpture—material with a clarity of line and reflection so immediate that the eye can fly across it," says Zadikian.'};return $APP.Gn.i?$APP.Gn.i("p",e):$APP.Gn.call(null,"p",e)}(),function(){var e={className:"mb-6 italic",children:"For Shafrazi, the work's insistence on touch is central: \" It's haptic. Do you know how important that is? That's what makes it. \""};return $APP.Gn.i?
$APP.Gn.i("p",e):$APP.Gn.call(null,"p",e)}(),function(){var e={className:"mb-6",children:"The Pavilion privileges a form of seeing grounded in the body—through weight, temperature, balance, and texture—rather than spectacle or narrative. Units will be cast, stacked, dismantled, and restacked throughout the exhibition, remaining in constant motion."};return $APP.Gn.i?$APP.Gn.i("p",e):$APP.Gn.call(null,"p",e)}(),function(){var e=function(){return{className:"mb-6",children:["By presenting the studio in its raw, working state—without performance or theatrical staging—",
function(){var f={className:"font-bold text-pink-400",children:"THE STUDIO "};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}(),"aligns closely with the Biennale's curatorial framework, ",function(){var f={className:"italic",children:"In Minor Keys"};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}(),". The work responds not with commentary or illustration, but with material intelligence, meditative clarity, and poetic restraint—tuning visitors to the lower frequencies: the modest, the elemental, the sanctuary."]}}();
return $APP.Hn.i?$APP.Hn.i("p",e):$APP.Hn.call(null,"p",e)}(),function(){var e={className:"mb-6",children:"The project marks an inner shift for Zadikian, turning away from the bombast of gold toward a quieter thread that has long run through his practice: plaster and pigment. The work foregrounds the rigor, repetition, and material intelligence that have underpinned his oeuvre for decades."};return $APP.Gn.i?$APP.Gn.i("p",e):$APP.Gn.call(null,"p",e)}(),function(){var e={className:"font-bold text-pink-400",
children:"THE STUDIO "};e={children:["In a cultural moment dominated by speed, novelty, and distraction, ",$APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e),"turns toward repetition, exactitude, and touch. Drawing on childhood experiences working with Armenian tuff stone and a lifelong intimacy with plaster, Zadikian produces units that appear plain at first glance, yet reveal unexpected depth through surface, edge, and volume. Together, they form a precise yet open-ended vocabulary—a language of blocks, strata, and intervals that underwrites a larger meditation on resilience, renewal, and the rediscovery of origins."]};
return $APP.Hn.i?$APP.Hn.i("p",e):$APP.Hn.call(null,"p",e)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",d):$APP.Hn.call(null,"div",d)}():null,$APP.lb(b)?function(){var d=function(){return{className:"flex justify-center p-4 mt-6",children:function(){var e=function(){return{"on-click":function(){var f=$APP.lb(b);return c.j?c.j(f):c.call(null,f)},"class":"px-8 py-3",title:"Read more"}}();return $APP.Gn.i?$APP.Gn.i($APP.Qn,e):$APP.Gn.call(null,$APP.Qn,e)}()}}();return $APP.Gn.i?$APP.Gn.i("div",d):$APP.Gn.call(null,
"div",d)}():null]}}();return $APP.Hn.i?$APP.Hn.i("div",a):$APP.Hn.call(null,"div",a)};
tq=function(a){$APP.nq(a);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));a=function(){return{"section-id":"budget-section",children:function(){var b=function(){return{className:"w-full h-full\n               text-white\n               grey-grad\n               flex items-center justify-center flex-col",children:function(){var c=function(){return{className:"flex flex-col w-full lg:w-8/12",children:[function(){var d={};return $APP.Gn.i?$APP.Gn.i(qq,d):$APP.Gn.call(null,qq,d)}(),
function(){var d={};return $APP.Gn.i?$APP.Gn.i(lr,d):$APP.Gn.call(null,lr,d)}(),function(){var d={};return $APP.Gn.i?$APP.Gn.i(rq,d):$APP.Gn.call(null,rq,d)}(),function(){var d={};return $APP.Gn.i?$APP.Gn.i(pq,d):$APP.Gn.call(null,pq,d)}(),function(){var d={};return $APP.Gn.i?$APP.Gn.i(sq,d):$APP.Gn.call(null,sq,d)}(),function(){var d={};return $APP.Gn.i?$APP.Gn.i($APP.so,d):$APP.Gn.call(null,$APP.so,d)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",c):$APP.Hn.call(null,"div",c)}()}}();return $APP.Gn.i?
$APP.Gn.i("div",b):$APP.Gn.call(null,"div",b)}()}}();return $APP.Gn.l?$APP.Gn.l($APP.ao,a,"budget-section"):$APP.Gn.call(null,$APP.ao,a,"budget-section")};
$APP.hr=function(a,b){a=new $APP.U(null,2,5,$APP.X,[$APP.nq(a),b],null);a=$APP.O(a,0,null);a=$APP.S(a);var c=$APP.Gb(a,Dw),d=$APP.Gb(a,Ew),e=$APP.Gb(a,Fw);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));var f=$APP.Dp("comp-ref");a=$APP.Hp(function(){return $APP.w(c)?d.B?d.B():d.call(null):$APP.sp.gsap.to($APP.A(f),{opacity:0,onComplete:e,duration:1})});b=[c];$APP.yp.i?$APP.yp.i(a,b):$APP.yp.call(null,a,b);a=function(){var h={};h=$APP.Gn.i?$APP.Gn.i(tq,h):$APP.Gn.call(null,tq,h);
return{ref:f,children:h}}();return $APP.Gn.i?$APP.Gn.i("div",a):$APP.Gn.call(null,"div",a)};$APP.Jh.prototype.yd=Xw(0,function(a,b){return new $APP.Jh(this.Bc,$APP.Vb(this.Qb,b),null)});
var Wi=function Wi(a){switch(arguments.length){case 0:return Wi.B();case 1:return Wi.j(arguments[0]);case 2:return Wi.i(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Wi.G(arguments[0],arguments[1],2<c.length?new $APP.cd(c.slice(2),0,null):null)}};Wi.B=function(){return 0};Wi.j=function(a){return a};Wi.i=function(a,b){return a+b};Wi.G=function(a,b,c){return $APP.tb(Wi,a+b,c)};
Wi.V=function(a){var b=$APP.H(a),c=$APP.I(a);a=$APP.H(c);c=$APP.I(c);return this.G(b,a,c)};Wi.sd=2;var Wd=function Wd(a){switch(arguments.length){case 1:return Wd.j(arguments[0]);case 2:return Wd.i(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Wd.G(arguments[0],arguments[1],2<c.length?new $APP.cd(c.slice(2),0,null):null)}};Wd.j=function(a){return a};Wd.i=function(a,b){return a==null?null:Zb(a,b)};
Wd.G=function(a,b,c){for(;;){if(a==null)return null;a=Wd.i(a,b);if($APP.w(c))b=$APP.H(c),c=$APP.I(c);else return a}};Wd.V=function(a){var b=$APP.H(a),c=$APP.I(a);a=$APP.H(c);c=$APP.I(c);return this.G(b,a,c)};Wd.sd=2;
var Fw=new $APP.E(null,"outro-complete-callback","outro-complete-callback",-1973874519),tw=new $APP.E(null,"amount","amount",364489504),Cw=new $APP.E(null,"on-exit","on-exit",1821961613),Bw=new $APP.E(null,"root-margin","root-margin",-1598874814),yw=new $APP.E(null,"set-expanded-items","set-expanded-items",-112840979),uw=new $APP.E(null,"cost-data","cost-data",-1991336764),zw=new $APP.E(null,"expanded-items","expanded-items",749320313),Aw=new $APP.E(null,"threshold","threshold",204221583),Ew=new $APP.E(null,
"intro-complete-callback","intro-complete-callback",1121849196),Dw=new $APP.E(null,"active","active",1895962068),ww=new $APP.E(null,"detail","detail",-1545345025),vw=new $APP.E(null,"details","details",1956795411),xw=new $APP.E(null,"item","item",249373802);$APP.Xl("budget-view");$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(Fp,"",null,null):(void 0).call(null,Fp,"",null,null)),$APP.oq(Fp,"amp.components.elements.budget-table/total-section"));$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(Ip,"",null,null):(void 0).call(null,Ip,"",null,null)),$APP.oq(Ip,"amp.components.elements.budget-table/detail-line-item"));
$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(Jp,"",null,null):(void 0).call(null,Jp,"",null,null)),$APP.oq(Jp,"amp.components.elements.budget-table/section-line-item"));$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(Kp,"(hooks/use-state #{})",null,null):(void 0).call(null,Kp,"(hooks/use-state #{})",null,null)),$APP.oq(Kp,"amp.components.elements.budget-table/budget-table"));var Lp=new $APP.U(null,9,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Venue Ops",vw,new $APP.U(null,8,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Venue rent",tw,13E4],null),new $APP.v(null,2,[$APP.$u,"Staffing",tw,75E3],null),new $APP.v(null,2,[$APP.$u,"Utilities",tw,0],null),new $APP.v(null,2,[$APP.$u,"Permits \x26 insurance",tw,16E3],null),new $APP.v(null,2,[$APP.$u,"Construction",tw,17E3],null),new $APP.v(null,2,[$APP.$u,"Lighting",tw,7500],null),new $APP.v(null,2,[$APP.$u,"Taxes \x26 VAT",tw,53900],null),
new $APP.v(null,2,[$APP.$u,"Contingency",tw,30040],null)],null)],null),new $APP.v(null,2,[$APP.$u,"Administration",vw,new $APP.U(null,9,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Curators \x26 artists",tw,6E4],null),new $APP.v(null,2,[$APP.$u,"Admin support",tw,32500],null),new $APP.v(null,2,[$APP.$u,"Engineering",tw,4500],null),new $APP.v(null,2,[$APP.$u,"Legal \x26 accounting",tw,15E3],null),new $APP.v(null,2,[$APP.$u,"Bookkeeping \x26 HR",tw,6800],null),new $APP.v(null,2,[$APP.$u,"Software tools",tw,
900],null),new $APP.v(null,2,[$APP.$u,"Travel \x26 lodging",tw,44E3],null),new $APP.v(null,2,[$APP.$u,"Proposal travel",tw,16E3],null),new $APP.v(null,2,[$APP.$u,"Contingency",tw,16720],null)],null)],null),new $APP.v(null,2,[$APP.$u,"Production",vw,new $APP.U(null,19,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Foam core",tw,17500],null),new $APP.v(null,2,[$APP.$u,"Pigments",tw,12500],null),new $APP.v(null,2,[$APP.$u,"Plaster",tw,3750],null),new $APP.v(null,2,[$APP.$u,"Gold leaf",tw,35E3],null),new $APP.v(null,
2,[$APP.$u,"Gold sizing",tw,3530],null),new $APP.v(null,2,[$APP.$u,"Glass",tw,3E3],null),new $APP.v(null,2,[$APP.$u,"Studio rent",tw,15360],null),new $APP.v(null,2,[$APP.$u,"Utilities \x26 ins.",tw,7200],null),new $APP.v(null,2,[$APP.$u,"Gilders",tw,33600],null),new $APP.v(null,2,[$APP.$u,"Casters",tw,72E3],null),new $APP.v(null,2,[$APP.$u,"Assistants",tw,24E3],null),new $APP.v(null,2,[$APP.$u,"Crates",tw,15E3],null),new $APP.v(null,2,[$APP.$u,"Supplies",tw,1E4],null),new $APP.v(null,2,[$APP.$u,"Packing labor",
tw,6E3],null),new $APP.v(null,2,[$APP.$u,"Shipping LA–Venice",tw,3E4],null),new $APP.v(null,2,[$APP.$u,"Shipping Venice–LA",tw,3E4],null),new $APP.v(null,2,[$APP.$u,"Insurance",tw,12E3],null),new $APP.v(null,2,[$APP.$u,"Install crew",tw,16200],null),new $APP.v(null,2,[$APP.$u,"Contingency",tw,34914],null)],null)],null),new $APP.v(null,2,[$APP.$u,"Logistics",vw,new $APP.U(null,9,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Port handling",tw,2500],null),new $APP.v(null,2,[$APP.$u,"Barge transport",tw,6E3],
null),new $APP.v(null,2,[$APP.$u,"Local trucking",tw,2400],null),new $APP.v(null,2,[$APP.$u,"Forklift \x26 crew",tw,1800],null),new $APP.v(null,2,[$APP.$u,"Short storage",tw,1200],null),new $APP.v(null,2,[$APP.$u,"Crate storage",tw,2E3],null),new $APP.v(null,2,[$APP.$u,"Waste removal",tw,1E3],null),new $APP.v(null,2,[$APP.$u,"Reverse logistics",tw,6700],null),new $APP.v(null,2,[$APP.$u,"Contingency",tw,2240],null)],null)],null),new $APP.v(null,2,[$APP.$u,"Opening Week",vw,new $APP.U(null,18,5,$APP.X,
[new $APP.v(null,2,[$APP.$u,"Catering food",tw,7E3],null),new $APP.v(null,2,[$APP.$u,"Catering drinks",tw,2250],null),new $APP.v(null,2,[$APP.$u,"Event staff",tw,2500],null),new $APP.v(null,2,[$APP.$u,"Coordinator",tw,3E3],null),new $APP.v(null,2,[$APP.$u,"Security",tw,1200],null),new $APP.v(null,2,[$APP.$u,"Rentals",tw,2500],null),new $APP.v(null,2,[$APP.$u,"A/V \x26 tech",tw,1500],null),new $APP.v(null,2,[$APP.$u,"Event media",tw,2500],null),new $APP.v(null,2,[$APP.$u,"Invitations",tw,1E3],null),
new $APP.v(null,2,[$APP.$u,"VIP staff",tw,5500],null),new $APP.v(null,2,[$APP.$u,"Protocol support",tw,1E3],null),new $APP.v(null,2,[$APP.$u,"Press materials",tw,900],null),new $APP.v(null,2,[$APP.$u,"Interpreter",tw,700],null),new $APP.v(null,2,[$APP.$u,"Water taxis",tw,960],null),new $APP.v(null,2,[$APP.$u,"Public talks",tw,1200],null),new $APP.v(null,2,[$APP.$u,"Accessibility",tw,250],null),new $APP.v(null,2,[$APP.$u,"Signage",tw,300],null),new $APP.v(null,2,[$APP.$u,"Contingency",tw,3606],null)],
null)],null),new $APP.v(null,2,[$APP.$u,"Studio Ops",vw,new $APP.U(null,9,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Part-time staff",tw,18E3],null),new $APP.v(null,2,[$APP.$u,"Full-time staff",tw,3E4],null),new $APP.v(null,2,[$APP.$u,"Temp staff",tw,25E3],null),new $APP.v(null,2,[$APP.$u,"Materials",tw,5E3],null),new $APP.v(null,2,[$APP.$u,"Expendables",tw,7E3],null),new $APP.v(null,2,[$APP.$u,"Equipment",tw,7500],null),new $APP.v(null,2,[$APP.$u,"Lodging \x26 per diem",tw,4E4],null),new $APP.v(null,
2,[$APP.$u,"Waste",tw,1400],null),new $APP.v(null,2,[$APP.$u,"Contingency",tw,13390],null)],null)],null),new $APP.v(null,2,[$APP.$u,"Marketing",vw,new $APP.U(null,17,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Visual identity",tw,12500],null),new $APP.v(null,2,[$APP.$u,"Press kit",tw,7500],null),new $APP.v(null,2,[$APP.$u,"Website",tw,12E3],null),new $APP.v(null,2,[$APP.$u,"OOH design",tw,3500],null),new $APP.v(null,2,[$APP.$u,"Exhibition graphics",tw,5E3],null),new $APP.v(null,2,[$APP.$u,"Copywriting",
tw,1500],null),new $APP.v(null,2,[$APP.$u,"PR writing",tw,3500],null),new $APP.v(null,2,[$APP.$u,"OOH placement",tw,8400],null),new $APP.v(null,2,[$APP.$u,"Posters",tw,8E3],null),new $APP.v(null,2,[$APP.$u,"Social ads",tw,5E3],null),new $APP.v(null,2,[$APP.$u,"Campaign mgmt",tw,5E3],null),new $APP.v(null,2,[$APP.$u,"Digital ads",tw,7500],null),new $APP.v(null,2,[$APP.$u,"Print ads",tw,1E4],null),new $APP.v(null,2,[$APP.$u,"PR pre-opening",tw,1E4],null),new $APP.v(null,2,[$APP.$u,"PR ongoing",tw,1E4],
null),new $APP.v(null,2,[$APP.$u,"Marketing fee",tw,7500],null),new $APP.v(null,2,[$APP.$u,"Contingency",tw,11690],null)],null)],null),new $APP.v(null,2,[$APP.$u,"Publication",vw,new $APP.U(null,13,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Curatorial essay",tw,2500],null),new $APP.v(null,2,[$APP.$u,"Commissioned essays",tw,8E3],null),new $APP.v(null,2,[$APP.$u,"Artist texts",tw,1500],null),new $APP.v(null,2,[$APP.$u,"Wall texts",tw,1500],null),new $APP.v(null,2,[$APP.$u,"Catalogue design",tw,1E4],null),
new $APP.v(null,2,[$APP.$u,"Editing \x26 layout",tw,7500],null),new $APP.v(null,2,[$APP.$u,"Catalogue print",tw,24E3],null),new $APP.v(null,2,[$APP.$u,"Tote design",tw,3500],null),new $APP.v(null,2,[$APP.$u,"Tote printing",tw,4500],null),new $APP.v(null,2,[$APP.$u,"Stationery design",tw,2500],null),new $APP.v(null,2,[$APP.$u,"Stationery print",tw,1500],null),new $APP.v(null,2,[$APP.$u,"Misc \x26 proofs",tw,1750],null),new $APP.v(null,2,[$APP.$u,"Contingency",tw,6875],null)],null)],null),new $APP.v(null,
2,[$APP.$u,"Documentation",vw,new $APP.U(null,11,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Camera rental",tw,1E4],null),new $APP.v(null,2,[$APP.$u,"Film crew",tw,24900],null),new $APP.v(null,2,[$APP.$u,"Sound recording",tw,2800],null),new $APP.v(null,2,[$APP.$u,"Install photos",tw,1750],null),new $APP.v(null,2,[$APP.$u,"Final photos",tw,1800],null),new $APP.v(null,2,[$APP.$u,"Event photos",tw,1400],null),new $APP.v(null,2,[$APP.$u,"Film editing",tw,5400],null),new $APP.v(null,2,[$APP.$u,"Sound mix",tw,
1600],null),new $APP.v(null,2,[$APP.$u,"Social clips",tw,6E3],null),new $APP.v(null,2,[$APP.$u,"Archiving",tw,750],null),new $APP.v(null,2,[$APP.$u,"Contingency",tw,5640],null)],null)],null)],null);$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(pq,"",null,null):(void 0).call(null,pq,"",null,null)),$APP.oq(pq,"amp.components.sections.budget-section/cost-breakdown"));
$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(qq,"",null,null):(void 0).call(null,qq,"",null,null)),$APP.oq(qq,"amp.components.sections.budget-section/header"));
$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(rq,'(use-touch-enabled)(hooks/use-ref "outer-ctx")(use-intersection-observer outer-ctx)',null,null):(void 0).call(null,rq,'(use-touch-enabled)(hooks/use-ref "outer-ctx")(use-intersection-observer outer-ctx)',null,null)),$APP.oq(rq,"amp.components.sections.budget-section/about"));
$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(sq,"",null,null):(void 0).call(null,sq,"",null,null)),$APP.oq(sq,"amp.components.sections.budget-section/non-profit"));$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(lr,"(hooks/use-state false)",null,null):(void 0).call(null,lr,"(hooks/use-state false)",null,null)),$APP.oq(lr,"amp.components.sections.budget-section/press-release"));
$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(tq,"",null,null):(void 0).call(null,tq,"",null,null)),$APP.oq(tq,"amp.components.sections.budget-section/budget-section"));$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F($APP.hr,'(hooks/use-ref "comp-ref")(hooks/use-layout-effect [active] (if active (intro-complete-callback) (.to gsap (clojure.core/deref comp-ref) {:opacity 0, :onComplete outro-complete-callback, :duration 1})))',null,null):(void 0).call(null,$APP.hr,'(hooks/use-ref "comp-ref")(hooks/use-layout-effect [active] (if active (intro-complete-callback) (.to gsap (clojure.core/deref comp-ref) {:opacity 0, :onComplete outro-complete-callback, :duration 1})))',
null,null)),$APP.oq($APP.hr,"amp.views.budget-view/budget-view"));$APP.Vl.Yf();
}).call(this);