(function(){
'use strict';var Xw,sw,yw,Zb,Yi,Vw,zw,lp,xp,Fp,Ip,Jp,Kp,pr,qr,Ow,Fw,Sw,pq,Ew,qq,rq,sq,lr,Jw,tq;Xw=function(a,b){return $APP.vj[a]=b};
sw=function(a,b){a=new $APP.U(null,2,5,$APP.X,[$APP.nq(a),b],null);a=$APP.O(a,0,null);a=$APP.S(a);a=$APP.Gb(a,$APP.Tu);a=$APP.lq(a);b={strokeLinecap:"round",strokeLinejoin:"round",d:"m8.25 4.5 7.5 7.5-7.5 7.5"};b=$APP.Gn.i?$APP.Gn.i("path",b):$APP.Gn.call(null,"path",b);a={xmlns:"http://www.w3.org/2000/svg",fill:"none",viewBox:"0 0 24 24",strokeWidth:1.5,stroke:"currentColor",className:a,children:b};return $APP.Gn.i?$APP.Gn.i("svg",a):$APP.Gn.call(null,"svg",a)};
yw=function(a,b){a=new $APP.U(null,2,5,$APP.X,[$APP.nq(a),b],null);a=$APP.O(a,0,null);b={strokeLinecap:"round",strokeLinejoin:"round",d:"m11.99 7.5 3.75-3.75m0 0 3.75 3.75m-3.75-3.75v16.499H4.49"};b={xmlns:"http://www.w3.org/2000/svg",fill:"none",viewBox:"0 0 24 24",strokeWidth:1.5,stroke:"currentColor",className:"size-6",children:$APP.Gn.i?$APP.Gn.i("path",b):$APP.Gn.call(null,"path",b)};a=$APP.Cj(b,$APP.ho(a));return $APP.Gn.i?$APP.Gn.i("svg",a):$APP.Gn.call(null,"svg",a)};
Zb=function(a,b){if(a!=null&&a.yd!=null)a=a.yd(a,b);else{var c=Zb[$APP.p(a==null?null:a)];if(c!=null)a=c.i?c.i(a,b):c.call(null,a,b);else if(c=Zb._,c!=null)a=c.i?c.i(a,b):c.call(null,a,b);else throw $APP.x("ISet.-disjoin",a);}return a};Yi=function(a){if($APP.ie(a))return(a&1)===0;throw Error(["Argument must be an integer: ",$APP.y.j(a)].join(""));};
Vw=function(){var a=function(){function c(e,f){var h=null;if(arguments.length>1){h=0;for(var k=Array(arguments.length-1);h<k.length;)k[h]=arguments[h+1],++h;h=new $APP.cd(k,0,null)}return d.call(this,e,h)}function d(e,f){f=$APP.O(f,0,null);e=e.current;return $APP.w(e)?$APP.sp.gsap.to(window,$APP.ti(new $APP.v(null,3,[$APP.oo,$APP.w(f)?f:.35,$APP.ro,new $APP.v(null,2,[$APP.ip,e,$APP.jp,!1],null),$APP.mq,"power2.inOut"],null))):null}c.sd=1;c.V=function(e){var f=$APP.H(e);e=$APP.ed(e);return d(f,e)};
c.G=d;return c}(),b=[];return $APP.Ap.i?$APP.Ap.i(a,b):$APP.Ap.call(null,a,b)};
zw=function(){var a=$APP.S($APP.Ed([new $APP.v(null,1,[$APP.oo,1],null)])),b=$APP.Pb(a,$APP.oo,.35);a=function(){function d(f){var h=null;if(arguments.length>0){h=0;for(var k=Array(arguments.length-0);h<k.length;)k[h]=arguments[h+0],++h;h=new $APP.cd(k,0,null)}return e.call(this,h)}function e(){$APP.Ti(new $APP.v(null,2,[$APP.jn,$APP.hv,$APP.oo,b],null));return $APP.sp.gsap.to(window,$APP.ti(new $APP.v(null,3,[$APP.oo,b,$APP.ro,new $APP.v(null,1,[$APP.ip,0],null),$APP.mq,"power2.inOut"],null)))}d.sd=
0;d.V=function(f){f=$APP.F(f);return e(f)};d.G=e;return d}();var c=[];return $APP.Ap.i?$APP.Ap.i(a,c):$APP.Ap.call(null,a,c)};lp=function(a){return["€",$APP.y.j(a.toLocaleString("en-US"))].join("")};xp=function(a){return $APP.se(Wi,$APP.Kf.i(Aw,a))};
Fp=function(a,b){a=new $APP.U(null,2,5,$APP.X,[$APP.nq(a),b],null);a=$APP.O(a,0,null);a=$APP.S(a);a=$APP.Gb(a,Bw);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));var c=$APP.se(Wi,$APP.Kf.i(function(e){return xp(Cw.j(e))},a)),d=c+c*.1;a=function(){return{className:"flex flex-col",children:[function(){var e=function(){return{className:"bg-slate-200 text-slate-900 flex justify-between items-center px-4 py-2 mt-4",children:[function(){var f={className:"text-xl italic",children:"Sub total"};
f={className:"w-6/12 ",children:$APP.Gn.i?$APP.Gn.i("h3",f):$APP.Gn.call(null,"h3",f)};return $APP.Gn.i?$APP.Gn.i("div",f):$APP.Gn.call(null,"div",f)}(),function(){var f={className:"w-1/12 "};return $APP.Gn.i?$APP.Gn.i("div",f):$APP.Gn.call(null,"div",f)}(),function(){var f={className:"font-medium ",children:lp(c)};f={className:"w-4/12 flex justify-end items-center space-x-4 ",children:$APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)};return $APP.Gn.i?$APP.Gn.i("div",f):$APP.Gn.call(null,
"div",f)}(),function(){var f={className:"w-1/12"};return $APP.Gn.i?$APP.Gn.i("div",f):$APP.Gn.call(null,"div",f)}()]}}();return $APP.Hn.i?$APP.Hn.i("li",e):$APP.Hn.call(null,"li",e)}(),function(){var e=function(){return{className:"bg-slate-300 text-slate-900 flex justify-between items-center px-4 py-2",children:[function(){var f={className:"text-xl italic",children:"Contingency 10%"};f={className:"w-6/12 ",children:$APP.Gn.i?$APP.Gn.i("h3",f):$APP.Gn.call(null,"h3",f)};return $APP.Gn.i?$APP.Gn.i("div",
f):$APP.Gn.call(null,"div",f)}(),function(){var f={className:"w-1/12 "};return $APP.Gn.i?$APP.Gn.i("div",f):$APP.Gn.call(null,"div",f)}(),function(){var f={className:"font-medium ",children:lp(c*.1)};f={className:"w-4/12 flex justify-end items-center space-x-4 ",children:$APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)};return $APP.Gn.i?$APP.Gn.i("div",f):$APP.Gn.call(null,"div",f)}(),function(){var f={className:"w-1/12"};return $APP.Gn.i?$APP.Gn.i("div",f):$APP.Gn.call(null,"div",f)}()]}}();
return $APP.Hn.i?$APP.Hn.i("li",e):$APP.Hn.call(null,"li",e)}(),function(){var e=function(){return{className:"bg-slate-200 text-slate-900 flex justify-between items-center px-4 py-4",children:[function(){var f={className:"font-semibold text-2xl",children:"TOTAL"};f={className:"w-6/12 ",children:$APP.Gn.i?$APP.Gn.i("h3",f):$APP.Gn.call(null,"h3",f)};return $APP.Gn.i?$APP.Gn.i("div",f):$APP.Gn.call(null,"div",f)}(),function(){var f={className:"w-1/12 "};return $APP.Gn.i?$APP.Gn.i("div",f):$APP.Gn.call(null,
"div",f)}(),function(){var f={className:"font-medium ",children:lp(d)};f={className:"w-4/12 flex justify-end items-center space-x-4 ",children:$APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)};return $APP.Gn.i?$APP.Gn.i("div",f):$APP.Gn.call(null,"div",f)}(),function(){var f={className:"w-1/12"};return $APP.Gn.i?$APP.Gn.i("div",f):$APP.Gn.call(null,"div",f)}()]}}();return $APP.Hn.i?$APP.Hn.i("li",e):$APP.Hn.call(null,"li",e)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",a):$APP.Hn.call(null,"div",
a)};
Ip=function(a,b){a=new $APP.U(null,2,5,$APP.X,[$APP.nq(a),b],null);a=$APP.O(a,0,null);a=$APP.S(a);var c=$APP.Gb(a,$APP.jv),d=$APP.Gb(a,Dw);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));var e=!Yi(c);a=function(){return{className:$APP.lq(["px-8 py-2 flex justify-between items-center ",e?"bg-slate-700/50":""].join("")),children:[function(){var f=c+1;f={className:"font-mono text-sm text-slate-400 mr-4",children:[f<10?["0",$APP.y.j(f)].join(""):$APP.y.j(f),"."].join("")};return $APP.Gn.i?$APP.Gn.i("span",
f):$APP.Gn.call(null,"span",f)}(),function(){var f={className:"justify-start flex-1",children:$APP.$u.j(d)};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}(),function(){var f={className:"text-slate-300 font-medium",children:lp(Aw.j(d))};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}()]}}();return $APP.Hn.i?$APP.Hn.i("li",a):$APP.Hn.call(null,"li",a)};
Jp=function(a,b){a=new $APP.U(null,2,5,$APP.X,[$APP.nq(a),b],null);a=$APP.O(a,0,null);a=$APP.S(a);b=$APP.Gb(a,$APP.jv);var c=$APP.Gb(a,Hw),d=$APP.Gb(a,Iw),e=$APP.Gb(a,Kw);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));var f=$APP.Dp(["section-",$APP.y.j(b)].join("")),h=Vw(),k=["item-",$APP.y.j(b)].join(""),l=xp(Cw.j(c)),m=!Yi(b);a=function(){return{ref:f,className:$APP.lq(["overflow-hidden ",m?"":"bg-slate-800"].join("")),children:[function(){var n=function(){return{className:"flex justify-between items-center px-4 py-4 cursor-pointer transition-colors",
onClick:function(){function q(r){return $APP.w(r.j?r.j(k):r.call(null,k))?Wd.i(r,k):$APP.Kd.i(r,k)}return d.j?d.j(q):d.call(null,q)},children:[function(){var q={className:"font-semibold text-xl",children:$APP.$u.j(c)};q={className:"w-6/12 ",children:$APP.Gn.i?$APP.Gn.i("h3",q):$APP.Gn.call(null,"h3",q)};return $APP.Gn.i?$APP.Gn.i("div",q):$APP.Gn.call(null,"div",q)}(),function(){var q={className:"w-1/12 "};return $APP.Gn.i?$APP.Gn.i("div",q):$APP.Gn.call(null,"div",q)}(),function(){var q={className:"font-medium",
children:lp(l)};q={className:"w-4/12 flex justify-end items-center ",children:$APP.Gn.i?$APP.Gn.i("span",q):$APP.Gn.call(null,"span",q)};return $APP.Gn.i?$APP.Gn.i("div",q):$APP.Gn.call(null,"div",q)}(),function(){var q=$APP.lq(["w-5 h-5 transition-transform ",$APP.w(e.j?e.j(k):e.call(null,k))?"rotate-90":null].join(""));var r={};r=$APP.Gn.i?$APP.Gn.i(sw,r):$APP.Gn.call(null,sw,r);q={className:q,children:r};q={className:"w-1/12 flex justify-end items-center ",children:$APP.Gn.i?$APP.Gn.i("div",q):
$APP.Gn.call(null,"div",q)};return $APP.Gn.i?$APP.Gn.i("div",q):$APP.Gn.call(null,"div",q)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",n):$APP.Hn.call(null,"div",n)}(),$APP.w(e.j?e.j(k):e.call(null,k))?function(){var n=function(){return{className:"border-l-8 border-slate-600",children:[function(){var q=function(){return{className:"",children:[function(){var r={className:"px-8 py-4 italic",children:Lw.j(c)};r={className:"text-base bg-slate-200/10 text-white",children:$APP.Gn.i?$APP.Gn.i("p",r):$APP.Gn.call(null,
"p",r)};return $APP.Gn.i?$APP.Gn.i("div",r):$APP.Gn.call(null,"div",r)}(),function(){var r=function(){return{className:"",children:$APP.sg(function(u,z){z={idx:u,detail:z};u=["detail-",$APP.y.j(u)].join("");return $APP.Gn.l?$APP.Gn.l(Ip,z,u):$APP.Gn.call(null,Ip,z,u)},Cw.j(c))}}();return $APP.Gn.i?$APP.Gn.i("ol",r):$APP.Gn.call(null,"ol",r)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",q):$APP.Hn.call(null,"div",q)}(),function(){var q=function(){return{className:"bg-blue-900 flex flex-col",children:[function(){var r=
function(){return{className:"font-semibold text-xl px-8 py-4  flex",children:[function(){var u={className:"font-mono text-sm text-slate-400",children:"-"};return $APP.Gn.i?$APP.Gn.i("span",u):$APP.Gn.call(null,"span",u)}(),function(){var u=function(){return{className:"flex justify-between ml-8 w-full text-blue-100",children:[function(){var z={children:"Total: "};return $APP.Gn.i?$APP.Gn.i("span",z):$APP.Gn.call(null,"span",z)}(),function(){var z={children:lp(l)};return $APP.Gn.i?$APP.Gn.i("span",
z):$APP.Gn.call(null,"span",z)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",u):$APP.Hn.call(null,"div",u)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",r):$APP.Hn.call(null,"div",r)}(),function(){var r=function(){return{className:"bg-slate-800 flex p-4 justify-center items-center cursor-pointer",onClick:function(){function u(z){return $APP.w(z.j?z.j(k):z.call(null,k))?Wd.i(z,k):$APP.Kd.i(z,k)}d.j?d.j(u):d.call(null,u);return h.j?h.j(f):h.call(null,f)},children:["CLOSE SECTION",function(){var u=$APP.lq(["w-5 h-5 transition-transform ml-4 ",
$APP.w(e.j?e.j(k):e.call(null,k))?"-rotate-90":null].join(""));var z={};z=$APP.Gn.i?$APP.Gn.i(sw,z):$APP.Gn.call(null,sw,z);u={className:u,children:z};return $APP.Gn.i?$APP.Gn.i("div",u):$APP.Gn.call(null,"div",u)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",r):$APP.Hn.call(null,"div",r)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",q):$APP.Hn.call(null,"div",q)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",n):$APP.Hn.call(null,"div",n)}():null]}}();return $APP.Hn.i?$APP.Hn.i("li",a):$APP.Hn.call(null,"li",a)};
Kp=function(a,b){a=new $APP.U(null,2,5,$APP.X,[$APP.nq(a),b],null);a=$APP.O(a,0,null);a=$APP.S(a);var c=$APP.Gb(a,Bw);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));a=$APP.Cp($APP.Lh);var d=$APP.O(a,0,null),e=$APP.O(a,1,null);a=function(){return{className:"w-full text-white",children:[$APP.sg(function(f,h){h={idx:f,item:h,"set-expanded-items":e,"expanded-items":d};f=[$APP.y.j(f),"-section"].join("");return $APP.Gn.l?$APP.Gn.l(Jp,h,f):$APP.Gn.call(null,Jp,h,f)},c),function(){var f=
{"cost-data":c};return $APP.Gn.i?$APP.Gn.i(Fp,f):$APP.Gn.call(null,Fp,f)}()]}}();return $APP.Hn.i?$APP.Hn.i("ol",a):$APP.Hn.call(null,"ol",a)};pr=function(a){for(var b=[],c=arguments.length,d=0;;)if(d<c)b.push(arguments[d]),d+=1;else break;return qr(arguments[0],1<b.length?new $APP.cd(b.slice(1),0,null):null)};
qr=function(a,b){b=$APP.S(b);var c=$APP.Pb(b,Mw,.1),d=$APP.Pb(b,Nw,"0px"),e=$APP.Gb(b,$APP.Jd),f=$APP.Gb(b,Pw),h=$APP.Cp(!1);b=$APP.O(h,0,null);var k=$APP.O(h,1,null);h=$APP.Cp(!1);var l=$APP.O(h,0,null),m=$APP.O(h,1,null);h=$APP.Hp(function(){if($APP.w($APP.A(a))){var q=new IntersectionObserver(function(r){r=$APP.F(r);for(var u=null,z=0,G=0;;)if(G<z){var D=u.ea(null,G),K=D.isIntersecting;k.j?k.j(K):k.call(null,K);$APP.w(K)&&(m.j?m.j(!0):m.call(null,!0),$APP.w(e)&&(e.j?e.j(D):e.call(null,D)));$APP.w(function(){var V=
$APP.lb(K);return V?l:V}())&&$APP.w(f)&&(f.j?f.j(D):f.call(null,D));G+=1}else if(r=$APP.F(r)){u=r;if($APP.de(u))r=$APP.Ec(u),z=$APP.Fc(u),u=r,D=$APP.N(r),r=z,z=D;else{D=$APP.H(u);var P=D.isIntersecting;k.j?k.j(P):k.call(null,P);$APP.w(P)&&(m.j?m.j(!0):m.call(null,!0),$APP.w(e)&&(e.j?e.j(D):e.call(null,D)));$APP.w(function(){var V=$APP.lb(P);return V?l:V}())&&$APP.w(f)&&(f.j?f.j(D):f.call(null,D));r=$APP.I(u);u=null;z=0}G=0}else return null},{threshold:c,rootMargin:d});q.observe($APP.A(a));return function(){return q.disconnect()}}return null});
var n=[a,c,d];$APP.Z.i?$APP.Z.i(h,n):$APP.Z.call(null,h,n);return new $APP.U(null,2,5,$APP.X,[l,b],null)};
Ow=function(a){$APP.nq(a);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));var b=$APP.Dp("container-ref"),c=$APP.Dp("button-ref"),d=zw();a=$APP.xn(b,$APP.Ed([$APP.qu,function(){return window.innerHeight-window.innerHeight/8},$APP.ae,"1000000px",$APP.Ge,!1,$APP.Bh,!1]));$APP.O(a,0,null);a=$APP.O(a,1,null);$APP.vn(c,$APP.Ed([$APP.nt,new $APP.v(null,1,[$APP.av,1],null),$APP.Ot,new $APP.v(null,1,[$APP.av,.7],null)]));$APP.Lu(new $APP.v(null,4,[$APP.vo,b,$APP.Fu,new $APP.v(null,2,[$APP.ip,
0,$APP.av,1],null),$APP.Hu,new $APP.v(null,2,[$APP.ip,-150,$APP.av,.25],null),$APP.Pt,a],null));a=function(){var e={};e=$APP.Gn.i?$APP.Gn.i(yw,e):$APP.Gn.call(null,yw,e);e={ref:c,className:"flex \n                           w-full\n                           h-full\n                           bg-pink-300\n                           opacity-90\n                           font-bold\n                           text-xl\n                           px-4\n                           white-space-no-wrap",
onClick:d,children:["To Top ",e]};e=$APP.Hn.i?$APP.Hn.i("div",e):$APP.Hn.call(null,"div",e);return{ref:b,className:"fixed right-0 cursor-pointer z-30",children:e}}();return $APP.Gn.i?$APP.Gn.i("div",a):$APP.Gn.call(null,"div",a)};
Fw=function(a,b){a=new $APP.U(null,2,5,$APP.X,[$APP.nq(a),b],null);a=$APP.O(a,0,null);b=$APP.S(a);a=$APP.Gb(b,Qw);b=$APP.Gb(b,$APP.Zi);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));a={aspectRatio:$APP.zq(a),width:$APP.zq("100%"),position:$APP.zq("relative"),overflow:$APP.zq("hidden")};b={style:{position:$APP.zq("absolute"),inset:$APP.zq(0)},children:b};b=$APP.Gn.i?$APP.Gn.i("div",b):$APP.Gn.call(null,"div",b);a={style:a,children:b};return $APP.Gn.i?$APP.Gn.i("div",a):$APP.Gn.call(null,
"div",a)};
Sw=function(a,b){a=new $APP.U(null,2,5,$APP.X,[$APP.nq(a),b],null);a=$APP.O(a,0,null);a=$APP.S(a);var c=$APP.Gb(a,$APP.jv),d=$APP.Gb(a,Rw),e=$APP.Gb(a,$APP.$u),f=$APP.Gb(a,$APP.Zi);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));a=function(){return{id:["section-",$APP.y.j(c)].join(""),children:[function(){var h=function(){return{className:"px-4 pt-12 text-slate-100",children:[function(){var k=function(){return{className:"mb-6 flex items-center gap-3",children:[function(){var l={className:"h-px w-10 bg-pink-500/70"};
return $APP.Gn.i?$APP.Gn.i("div",l):$APP.Gn.call(null,"div",l)}(),function(){var l={className:"text-sm tracking-[0.25em] uppercase text-slate-400",children:[$APP.y.j(c),". ",$APP.y.j(d)].join("")};return $APP.Gn.i?$APP.Gn.i("p",l):$APP.Gn.call(null,"p",l)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",k):$APP.Hn.call(null,"div",k)}(),function(){var k={className:"\n               \n               font-bold\n               uppercase\n               leading-none\n               text-5xl\n               md:text-7xl\n               ",
children:e};return $APP.Gn.i?$APP.Gn.i("h2",k):$APP.Gn.call(null,"h2",k)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",h):$APP.Hn.call(null,"div",h)}(),function(){var h={className:"text-xl text-white-100",children:f};return $APP.Gn.i?$APP.Gn.i("div",h):$APP.Gn.call(null,"div",h)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",a):$APP.Hn.call(null,"div",a)};
pq=function(a){$APP.nq(a);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));a=function(){return{idx:3,eyebrow:"FINANCIALS",title:"BUDGET",children:[function(){var b=function(){return{className:"text-xl text-slate-100 p-4",children:[function(){var c={children:["The Armenian Pavilion at the 61st Venice Biennale is a major international cultural undertaking—","structured to meet the standards of the most rigorous national presentations. "]};return $APP.Hn.i?$APP.Hn.i("span",c):$APP.Hn.call(null,
"span",c)}(),function(){var c={className:"text-slate-300",children:"With a total budget of approximately "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"font-bold text-white",children:"€1.4M"};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:" ("};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"font-bold text-white",children:"$1.6M USD"};
return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:"), the financial framework covers the full scope of "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"font-semibold text-pink-400",children:"production, installation, operations, communications,"};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:" and "};
return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"font-semibold text-pink-400",children:"documentation"};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:". "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"block mt-6",children:["As Armenia does not maintain a permanent national pavilion in Venice, a venue must be secured through rental—",
"as is customary for many smaller and non-permanent participating nations. "]};return $APP.Hn.i?$APP.Hn.i("span",c):$APP.Hn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:"The selected site is located outside the Biennale’s primary zones, enabling a significantly lower base rent—approximately "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"font-bold text-white",children:"€130,000"};return $APP.Gn.i?$APP.Gn.i("span",
c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:"—while remaining fully accredited and visible within the official Biennale structure. "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:"By contrast, venues within the Giardini or Arsenale—when available—typically begin at "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"font-bold text-white",
children:"€400,000"};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:" in base rent, before construction, staffing, utilities, logistics, and operating overhead. "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"block mt-6",children:"Crucially, the nature of "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"font-semibold text-pink-400",
children:"THE STUDIO"};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:" makes this venue choice not only strategic but essential. "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:"The work is conceived to be produced, refined, and evolved "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"font-semibold italic text-slate-100",
children:"on site"};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:", allowing the Pavilion to function simultaneously as exhibition space and working studio. "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:["This approach meets extremely tight production and installation deadlines while maintaining full artistic and technical control—","conditions that would be far more difficult, costly, or even impossible under a traditional off-site fabrication and transport model. "]};
return $APP.Hn.i?$APP.Hn.i("span",c):$APP.Hn.call(null,"span",c)}(),function(){var c={className:"block my-6",children:"Rather than directing the majority of resources toward a single, fixed monumental installation, the artist and team have deliberately taken another route. "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:"By producing the work on site, the Pavilion avoids the need for a pre-fabricated "};return $APP.Gn.i?
$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"font-semibold italic text-slate-100",children:"“grand object”"};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:" altogether. "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:"This decision reduces fabrication, crating, international shipping, and risk-related costs, while aligning more precisely with the broader conceptual goals: "};
return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"font-semibold text-pink-400",children:"process over spectacle, presence over monumentality,"};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:" and "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"font-semibold text-pink-400",children:"sustained making over static display"};return $APP.Gn.i?
$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:". "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"block mt-6",children:"In this sense, cost efficiency and artistic rigor are not in opposition but mutually reinforcing. "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:"The Pavilion’s structure distributes resources across time, labor, materials, and public engagement—rather than concentrating them into a single object whose expense would be driven largely by transport and scale rather than meaning. "};
return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c=function(){return{className:"block my-6",children:[function(){var d={className:"",children:"Despite these efficiencies, the overall cost of operating in Venice during the Biennale remains high. "};return $APP.Gn.i?$APP.Gn.i("span",d):$APP.Gn.call(null,"span",d)}(),function(){var d={className:"text-slate-300",children:"Venice’s unique geography, limited infrastructure, and extraordinary demand elevate costs across all categories—logistics, storage, labor, accommodations, and technical services. "};
return $APP.Gn.i?$APP.Gn.i("span",d):$APP.Gn.call(null,"span",d)}(),function(){var d={className:"text-slate-300",children:"These conditions are shared by all national pavilions and reflect the Biennale’s position as the most visible international platform in contemporary art. "};return $APP.Gn.i?$APP.Gn.i("span",d):$APP.Gn.call(null,"span",d)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",c):$APP.Hn.call(null,"div",c)}(),function(){var c={className:"mt-6",children:"Unlike projects that culminate at opening, this Pavilion is conceived as a"};
return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"font-semibold italic text-slate-100",children:"seven-month operational commitment"};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"text-slate-300",children:": a living environment that functions simultaneously as exhibition space, working studio, public forum, and diplomatic platform—requiring sustained staffing, materials, logistics, and institutional oversight throughout the duration of the Biennale. "};
return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"block mt-6",children:"Significant investment secures venue readiness and regulatory compliance, supports curatorial and administrative leadership, funds museum-scale fabrication and specialized craft, and addresses Venice-specific transport, storage, installation, and reverse logistics. "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c=function(){return{className:"block mt-6",
children:[function(){var d={className:"font-semibold text-pink-400",children:"THE STUDIO"};return $APP.Gn.i?$APP.Gn.i("span",d):$APP.Gn.call(null,"span",d)}(),function(){var d={className:"text-slate-300",children:" is budgeted as an ongoing on-site operation, ensuring continuous execution, maintenance, and evolution of the work across the exhibition period—distinguishing the Pavilion from static presentations. "};return $APP.Gn.i?$APP.Gn.i("span",d):$APP.Gn.call(null,"span",d)}()]}}();return $APP.Hn.i?
$APP.Hn.i("span",c):$APP.Hn.call(null,"span",c)}(),function(){var c={className:"block mt-6",children:"Public visibility and long-term legacy are strengthened through opening week programs, marketing and public relations, publication, and comprehensive film and photographic documentation—ensuring that the Pavilion’s impact extends into international media, scholarship, and institutional archives. "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"block mt-6",
children:"To support the scale of this undertaking, a dedicated fundraising committee has been formed to advance the Pavilion’s financial and philanthropic efforts. "};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"block mt-4 text-slate-300",children:"The committee is led by:"};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c=function(){return{className:"mt-3 ml-6 list-disc text-slate-100",children:[function(){var d=
{children:"Archbishop Hovnan Derderian"};return $APP.Gn.i?$APP.Gn.i("li",d):$APP.Gn.call(null,"li",d)}(),function(){var d={children:"Tony Shafrazi"};return $APP.Gn.i?$APP.Gn.i("li",d):$APP.Gn.call(null,"li",d)}(),function(){var d={children:"Rafi Ourfalian"};return $APP.Gn.i?$APP.Gn.i("li",d):$APP.Gn.call(null,"li",d)}(),function(){var d={children:"Khachik Khudikyan"};return $APP.Gn.i?$APP.Gn.i("li",d):$APP.Gn.call(null,"li",d)}(),function(){var d={children:"Andranik Torosyan"};return $APP.Gn.i?$APP.Gn.i("li",
d):$APP.Gn.call(null,"li",d)}(),function(){var d={children:"Aram Alajajian"};return $APP.Gn.i?$APP.Gn.i("li",d):$APP.Gn.call(null,"li",d)}(),function(){var d={children:"Vik Hovsepian"};return $APP.Gn.i?$APP.Gn.i("li",d):$APP.Gn.call(null,"li",d)}()]}}();return $APP.Hn.i?$APP.Hn.i("ul",c):$APP.Hn.call(null,"ul",c)}(),function(){var c={className:"block mt-4 text-slate-300",children:"The committee plays an active role in guiding outreach, stewarding donor relationships, and advancing the fundraising strategy necessary to realize a project of this ambition and international significance. "};
return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",c)}(),function(){var c={className:"block italic mt-6 font-normal text-lg text-slate-100",children:"A responsible contingency is included to accommodate the realities of an extended international project operating across jurisdictions, timelines, and currencies—ensuring stability, accountability, and the successful delivery of Armenia’s national presentation on the world stage."};return $APP.Gn.i?$APP.Gn.i("span",c):$APP.Gn.call(null,"span",
c)}()]}}();return $APP.Hn.i?$APP.Hn.i("p",b):$APP.Hn.call(null,"p",b)}(),function(){var b={"cost-data":Lp};return $APP.Gn.i?$APP.Gn.i(Kp,b):$APP.Gn.call(null,Kp,b)}()]}}();return $APP.Hn.i?$APP.Hn.i(Sw,a):$APP.Hn.call(null,Sw,a)};
Ew=function(a,b){a=new $APP.U(null,2,5,$APP.X,[$APP.nq(a),b],null);a=$APP.O(a,0,null);a=$APP.S(a);var c=$APP.Gb(a,$APP.$u),d=$APP.Gb(a,Tw);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));var e=$APP.yn();a=function(){return{onClick:function(){return e.j?e.j(d):e.call(null,d)},className:"hover:text-pink-400 transition-colors",children:[c," ",function(){var f={"class":"w-6 h-6 inline-block ml-1"};return $APP.Gn.i?$APP.Gn.i(sw,f):$APP.Gn.call(null,sw,f)}()]}}();return $APP.Hn.i?$APP.Hn.i("button",
a):$APP.Hn.call(null,"button",a)};
qq=function(a){$APP.nq(a);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));a=function(){return{className:"",children:[function(){var b={src:"images/graphics/biennale_logo.png"};b={className:"w-1/2 lg:w-1/4 lg:max-w-64 mt-4 lg:mt-8 px-4",children:$APP.Gn.i?$APP.Gn.i("img",b):$APP.Gn.call(null,"img",b)};return $APP.Gn.i?$APP.Gn.i("div",b):$APP.Gn.call(null,"div",b)}(),function(){var b={className:"font-helvetica font-bold text-5xl lg:text-6xl text-white mb-6",children:"ARMENIAN PAVILION 2026 VENICE BIENNALE"};
b={className:"px-4 mt-12 lg:mt-16 max-w-4xl",children:$APP.Gn.i?$APP.Gn.i("h1",b):$APP.Gn.call(null,"h1",b)};return $APP.Gn.i?$APP.Gn.i("div",b):$APP.Gn.call(null,"div",b)}(),function(){var b=function(){return{className:"w-full px-4 mt-16",children:function(){var c=function(){return{className:"text-2xl text-white space-y-4 flex flex-col justify-start items-start",children:[function(){var d={title:"1. Press Release",anchor:"section-1"};return $APP.Gn.i?$APP.Gn.i(Ew,d):$APP.Gn.call(null,Ew,d)}(),function(){var d=
{title:"2. Overview - THE STUDIO",anchor:"section-2"};return $APP.Gn.i?$APP.Gn.i(Ew,d):$APP.Gn.call(null,Ew,d)}(),function(){var d={title:"3. Budget",anchor:"section-3"};return $APP.Gn.i?$APP.Gn.i(Ew,d):$APP.Gn.call(null,Ew,d)}(),function(){var d={title:"4. Location Details",anchor:"section-4"};return $APP.Gn.i?$APP.Gn.i(Ew,d):$APP.Gn.call(null,Ew,d)}(),function(){var d={title:"5. Donation Info",anchor:"section-5"};return $APP.Gn.i?$APP.Gn.i(Ew,d):$APP.Gn.call(null,Ew,d)}()]}}();return $APP.Hn.i?
$APP.Hn.i("div",c):$APP.Hn.call(null,"div",c)}()}}();return $APP.Gn.i?$APP.Gn.i("div",b):$APP.Gn.call(null,"div",b)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",a):$APP.Hn.call(null,"div",a)};
rq=function(a){$APP.nq(a);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));a=function(){return{idx:2,eyebrow:"OVERVIEW",title:"THE STUDIO",children:function(){var b=function(){return{children:[function(){var c=function(){return{className:"space-y-8\n               p-4",children:[function(){var d={className:"font-bold text-pink-400",children:"THE STUDIO "};d={children:[$APP.Gn.i?$APP.Gn.i("span",d):$APP.Gn.call(null,"span",d),"is a sustained site of making: a working studio made visible, in full daylight, without theatrics. ",
"Over the duration of the Biennale, the Armenian Pavilion operates as a neutral armature in which objects are brought into being through repetition, calibration, and quiet labor—","an environment where the work can be encountered as work, and where meaning is inseparable from existence."]};return $APP.Hn.i?$APP.Hn.i("p",d):$APP.Hn.call(null,"p",d)}(),function(){var d=function(){return{children:["At its core is a simple form: ",function(){var e={className:"font-medium text-slate-100",children:"the unit, the block, the brick"};
return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),". Perhaps the most basic object of the modern world—foundational, common, and easily overlooked. ","This reduction is intentional. The work begins by coming to terms with a ",function(){var e={className:"italic",children:"Kantian"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}()," limit: that we will never encounter the thing as it is in itself. ","For ",function(){var e={className:"italic",children:"Immanuel Kant"};
return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),", the object always exceeds our grasp; it cannot be fully refined, fully labeled, or fully known. ","Here, the brick insists on that paradox: the more it is simplified, the more resistant it becomes to interpretation."]}}();return $APP.Hn.i?$APP.Hn.i("p",d):$APP.Hn.call(null,"p",d)}(),function(){var d={className:"font-medium",children:"measure, surface, weight, edge, join"};d={children:["The unit does not arrive as image or symbol. It arrives as a fact—built through internal necessity: ",
$APP.Gn.i?$APP.Gn.i("span",d):$APP.Gn.call(null,"span",d),". Sculpture is reduced to its most primitive condition, not to empty it of meaning, but to expose the conditions under which meaning fails. ","Like a coin worn smooth through use, the block does not tell us what it is; it asks whether we can tolerate its refusal to resolve."]};return $APP.Hn.i?$APP.Hn.i("p",d):$APP.Hn.call(null,"p",d)}(),function(){var d=function(){return{children:["This is why the studio itself matters. The act of making is not staged, but neither is it hidden. ",
"The object’s existence is not only shown; it is witnessed. ","As ",function(){var e={className:"font-semibold text-slate-100",children:"Tony Shafrazi"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}()," has described it, the pavilion offers the experience of being ",function(){var e={className:"italic",children:"“like a fly on the wall,”"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}()," of ",function(){var e={className:"italic",children:"“seeing and studying art in the making.”"};
return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}()," ","This is not a performance claim. It is an epistemic one: understanding shifts because the object’s coming-into-being is present. ","The work is not explained. It is verified through test, trial, correction, and return."]}}();return $APP.Hn.i?$APP.Hn.i("p",d):$APP.Hn.call(null,"p",d)}(),function(){var d={className:"font-medium",children:"plaster"};d={children:["The process is exacting by design. A famously unstable material—",
$APP.Gn.i?$APP.Gn.i("span",d):$APP.Gn.call(null,"span",d),"—is subjected to an uncompromising aim toward precision. ","Units are cast on flat glass, refined, sanded, calibrated. ","When blocks meet, they strive to read as one—so continuous that the hand passing over them cannot locate the seam. ","This is not fetish precision. It is a philosophical position made physical: an attempt to bring coherence to something that resists it."]};return $APP.Hn.i?$APP.Hn.i("p",d):$APP.Hn.call(null,"p",d)}(),function(){var d=
{children:"The studio does not conceal the truth that this aim can never be fully achieved. {Plaster shifts. Humidity intervenes. The hand decides. {Precision here is not purity; it is pursuit. {And it is the pursuit that transforms the object: something crosses a threshold when the artist returns again and again—measuring, flattening, correcting—{not to perfect the unit, but to test whether it can hold together. {In this striving, the block becomes something more than material. {It becomes an instance of existence asserting itself without interpretation.".split("{")};
return $APP.Hn.i?$APP.Hn.i("p",d):$APP.Hn.call(null,"p",d)}(),function(){var d={children:["This is the moment where Kant becomes tangible. Meaning does not arise from narrative or representation, but from the object’s right to exist as itself—unexhausted by what it appears to be. ","Making, in this sense, becomes a way of instantiating a universe—not metaphorically, but materially. ","A world is established the moment the unit becomes consistent with itself and consistent with the other units around it. ",
"As Shafrazi has observed, the transformation occurs after something is completed, understood, and then revisited—again and again. ","It is in this loop, not in expression or excess, that force accumulates."]};return $APP.Hn.i?$APP.Hn.i("p",d):$APP.Hn.call(null,"p",d)}(),function(){var d=function(){return{children:["Within the curatorial horizon of ",function(){var e={className:"italic font-medium",children:"In Minor Keys"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),", articulated by ",
function(){var e={className:"font-medium",children:"Koyo Kouoh"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),", ",function(){var e={className:"font-bold text-pink-400",children:"THE STUDIO "};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),"operates at a lower frequency. It refuses amplification. It refuses declaration. ","It offers instead an island of sustained attention—where the dignity of the object is safeguarded by the conditions of its making: ",
function(){var e={className:"font-medium",children:"slow, exacting, ongoing"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),". ","The encounter is redirected away from the habitual question, ",function(){var e={className:"italic",children:"What does it represent?"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),", toward a more difficult one:"]}}();return $APP.Hn.i?$APP.Hn.i("p",d):$APP.Hn.call(null,"p",d)}(),function(){var d=function(){return{className:"\n            mt-10\n            rounded-2xl\n            border\n            border-pink-500/20\n            bg-slate-900/40\n            p-6\n            md:p-8",
children:function(){var e=function(){return{className:"\n             text-2xl\n             md:text-3xl\n             leading-snug\n             text-slate-100",children:["What does it mean for something to exist—",function(){var f={className:"font-semibold",children:"plainly"};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}(),", ",function(){var f={className:"font-semibold",children:"rigorously"};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}(),", in front of you—without becoming an announcement?"]}}();
return $APP.Hn.i?$APP.Hn.i("p",e):$APP.Hn.call(null,"p",e)}()}}();return $APP.Gn.i?$APP.Gn.i("div",d):$APP.Gn.call(null,"div",d)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",c):$APP.Hn.call(null,"div",c)}(),function(){var c=function(){return{className:"space-y-4 mt-6",children:[function(){var d={"img-src":"https://atd-722658831.imgix.net/simple_blocks/FileName_001Beauty_ViewLayer_099-3.tif",caption:"BLUE YELLOW BLUE YELLOW",credit:"© Zadik Zadikian 2026"};return $APP.Gn.i?$APP.Gn.i($APP.kp,d):$APP.Gn.call(null,
$APP.kp,d)}(),function(){var d={"img-src":"https://atd-722658831.imgix.net/artwork/blue_unit_with_hand.tif"};return $APP.Gn.i?$APP.Gn.i($APP.kp,d):$APP.Gn.call(null,$APP.kp,d)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",c):$APP.Hn.call(null,"div",c)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",b):$APP.Hn.call(null,"div",b)}()}}();return $APP.Gn.i?$APP.Gn.i(Sw,a):$APP.Gn.call(null,Sw,a)};
sq=function(a){$APP.nq(a);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));a=function(){return{idx:5,eyebrow:"NON-PROFIT",title:"DONATION INFORMATION",children:function(){var b=function(){return{className:"space-y-8\n                   p-4",children:[function(){var c=function(){return{className:"mb-12 text-slate-300",children:[function(){var d=function(){return{children:["The Armenian Pavilion 2026 is supported through ",function(){var e={className:"font-semibold",children:"Fallen Angels Inc."};
return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),", a registered ",function(){var e={className:"font-semibold",children:"501(c)(3)"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}()," public non-profit organization. ",function(){var e={className:"font-semibold",children:"Contributions are tax deductible"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}()," to the extent permitted by law."]}}();return $APP.Hn.i?$APP.Hn.i("p",d):$APP.Hn.call(null,
"p",d)}(),function(){var d=function(){return{className:"mt-6 space-y-1",children:[function(){var e={className:"font-semibold",children:"Organization: "};e={children:[$APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e),"Fallen Angels Inc."]};return $APP.Hn.i?$APP.Hn.i("p",e):$APP.Hn.call(null,"p",e)}(),function(){var e=function(){return{children:[function(){var f={className:"font-semibold",children:"EIN: "};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}(),function(){var f=
{className:"font-bold text-slate-100",children:"92-2395513"};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}()]}}();return $APP.Hn.i?$APP.Hn.i("p",e):$APP.Hn.call(null,"p",e)}(),function(){var e=function(){return{children:[function(){var f={className:"font-semibold",children:"Located in: "};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}(),function(){var f={className:"font-bold text-slate-100",children:"Los Angeles, CA"};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,
"span",f)}()]}}();return $APP.Hn.i?$APP.Hn.i("p",e):$APP.Hn.call(null,"p",e)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",d):$APP.Hn.call(null,"div",d)}(),function(){var d=function(){return{className:"mt-10 grid grid-cols-1 lg:grid-cols-2 gap-10",children:[function(){var e=function(){return{children:[function(){var f={className:"italic font-normal text-slate-300",children:"Transfers"};f={className:"text-3xl font-helvetica font-bold text-slate-100 mb-4",children:["Domestic ",$APP.Gn.i?$APP.Gn.i("span",
f):$APP.Gn.call(null,"span",f)]};return $APP.Hn.i?$APP.Hn.i("p",f):$APP.Hn.call(null,"p",f)}(),function(){var f=function(){return{className:"space-y-3",children:[function(){var h=function(){return{className:"flex items-baseline justify-between gap-6",children:[function(){var k={className:"font-semibold",children:"Name:"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}(),function(){var k={className:"text-right",children:"Fallen Angels Inc."};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,
"span",k)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",h):$APP.Hn.call(null,"div",h)}(),function(){var h=function(){return{className:"flex items-baseline justify-between gap-6",children:[function(){var k={className:"font-semibold",children:"Routing:"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}(),function(){var k={className:"text-right font-bold text-slate-100 tracking-wide",children:"091311229"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}()]}}();return $APP.Hn.i?
$APP.Hn.i("div",h):$APP.Hn.call(null,"div",h)}(),function(){var h=function(){return{className:"flex items-baseline justify-between gap-6",children:[function(){var k={className:"font-semibold",children:"Account #:"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}(),function(){var k={className:"text-right font-bold text-slate-100 tracking-wide",children:"202535309341"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",h):$APP.Hn.call(null,
"div",h)}(),function(){var h=function(){return{className:"flex items-start justify-between gap-6",children:[function(){var k={className:"font-semibold",children:"Address:"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}(),function(){var k=function(){return{className:"text-right leading-snug",children:[function(){var l={children:"Choice Financial Group"};return $APP.Gn.i?$APP.Gn.i("p",l):$APP.Gn.call(null,"p",l)}(),function(){var l={children:"4501 23rd Avenue S"};return $APP.Gn.i?
$APP.Gn.i("p",l):$APP.Gn.call(null,"p",l)}(),function(){var l={children:"Fargo, ND 58104"};return $APP.Gn.i?$APP.Gn.i("p",l):$APP.Gn.call(null,"p",l)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",k):$APP.Hn.call(null,"div",k)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",h):$APP.Hn.call(null,"div",h)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",f):$APP.Hn.call(null,"div",f)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",e):$APP.Hn.call(null,"div",e)}(),function(){var e=function(){return{children:[function(){var f={className:"italic font-normal text-slate-300",
children:"Transfers"};f={className:"text-3xl font-helvetica font-bold text-slate-100 mb-4",children:["International ",$APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)]};return $APP.Hn.i?$APP.Hn.i("p",f):$APP.Hn.call(null,"p",f)}(),function(){var f=function(){return{className:"space-y-3",children:[function(){var h=function(){return{className:"flex items-baseline justify-between gap-6",children:[function(){var k={className:"font-semibold",children:"Name:"};return $APP.Gn.i?$APP.Gn.i("span",
k):$APP.Gn.call(null,"span",k)}(),function(){var k={className:"text-right",children:"Fallen Angels Inc."};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",h):$APP.Hn.call(null,"div",h)}(),function(){var h=function(){return{className:"flex items-baseline justify-between gap-6",children:[function(){var k={className:"font-semibold",children:"SWIFT/BIC:"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}(),function(){var k={className:"text-right font-bold text-slate-100 tracking-wide",
children:"CHFGUS44021"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",h):$APP.Hn.call(null,"div",h)}(),function(){var h=function(){return{className:"flex items-baseline justify-between gap-6",children:[function(){var k={className:"font-semibold",children:"ABA/Routing:"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}(),function(){var k={className:"text-right font-bold text-slate-100 tracking-wide",children:"091311229"};
return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",h):$APP.Hn.call(null,"div",h)}(),function(){var h=function(){return{className:"flex items-baseline justify-between gap-6",children:[function(){var k={className:"font-semibold",children:"IBAN/Account #:"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}(),function(){var k={className:"text-right font-bold text-slate-100 tracking-wide",children:"202535309341"};return $APP.Gn.i?$APP.Gn.i("span",
k):$APP.Gn.call(null,"span",k)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",h):$APP.Hn.call(null,"div",h)}(),function(){var h=function(){return{className:"flex items-start justify-between gap-6",children:[function(){var k={className:"font-semibold",children:"Address:"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}(),function(){var k=function(){return{className:"text-right leading-snug",children:[function(){var l={children:"Choice Financial Group"};return $APP.Gn.i?$APP.Gn.i("p",l):
$APP.Gn.call(null,"p",l)}(),function(){var l={children:"4501 23rd Avenue S"};return $APP.Gn.i?$APP.Gn.i("p",l):$APP.Gn.call(null,"p",l)}(),function(){var l={children:"Fargo, ND 58104"};return $APP.Gn.i?$APP.Gn.i("p",l):$APP.Gn.call(null,"p",l)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",k):$APP.Hn.call(null,"div",k)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",h):$APP.Hn.call(null,"div",h)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",f):$APP.Hn.call(null,"div",f)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",e):
$APP.Hn.call(null,"div",e)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",d):$APP.Hn.call(null,"div",d)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",c):$APP.Hn.call(null,"div",c)}(),function(){var c={className:"p-4 mt-10 text-sm md:text-base text-slate-400",children:"If you would like a receipt letter for your records, please include your name and email address with the transfer memo."};return $APP.Gn.i?$APP.Gn.i("p",c):$APP.Gn.call(null,"p",c)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",b):$APP.Hn.call(null,
"div",b)}()}}();return $APP.Gn.i?$APP.Gn.i(Sw,a):$APP.Gn.call(null,Sw,a)};
lr=function(a){$APP.nq(a);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));a=$APP.Cp(!1);var b=$APP.O(a,0,null),c=$APP.O(a,1,null);a=function(){return{idx:1,eyebrow:"NEWS",title:"PRESS RELEASE",children:[function(){var d=function(){return{className:"p-4",children:[function(){var e=function(){return{className:"",children:function(){var f=function(){return{className:"font-medium text-xl",children:[function(){var h={className:"italic",children:"Yerevan / Los Angeles / Venice — "};
return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}(),"The Ministry of Culture of the Republic of Armenia has selected ",function(){var h={className:"font-semibold",children:"Zadik Zadikian"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}()," to represent Armenia at the ",function(){var h={className:"font-semibold",children:"61st Venice Biennale Arte"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}()," in 2026. Led by legendary art dealer ",function(){var h=
{className:"font-semibold",children:"Tony Shafrazi"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}()," as Chief Curator, the Pavilion aligns with Armenia's broader commitment to elevating its cultural presence on the international stage..."]}}();return $APP.Hn.i?$APP.Hn.i("p",f):$APP.Hn.call(null,"p",f)}()}}();return $APP.Gn.i?$APP.Gn.i("div",e):$APP.Gn.call(null,"div",e)}(),$APP.w(b)?function(){var e=function(){return{className:"",children:[function(){var f={className:"mb-6",
children:"This collaboration marks a historic and deeply resonant moment in both Zadikian's and Shafrazi's lives and careers: a symbolic return to Armenia and a shared mission to present a world-class national Pavilion to a global audience."};return $APP.Gn.i?$APP.Gn.i("p",f):$APP.Gn.call(null,"p",f)}(),function(){var f=function(){return{className:"mb-6",children:["Zadikian—who left Soviet Armenia at nineteen and experienced a radical cultural rupture upon arriving in the United States—came of age artistically through an uncommon trajectory. From San Francisco during the height of the countercultural moment, working with ",
function(){var h={className:"italic",children:"Benjamin Bufano"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}(),", to New York, where he assisted ",function(){var h={className:"italic",children:"Richard Serra"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}()," on monumental oil-stick wall drawings—one of which Serra titled ",function(){var h={className:"italic",children:"Zadikian"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}(),"—the artist now returns with a project of uncommon ambition and conceptual rigor."]}}();
return $APP.Hn.i?$APP.Hn.i("p",f):$APP.Hn.call(null,"p",f)}(),function(){var f={className:"font-bold text-pink-400",children:"THE STUDIO "};f={className:"mb-6",children:[$APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f),"transforms the Armenian Pavilion into an active site of sustained, concentrated making. Throughout the Biennale, Zadikian and his team will fabricate primordial plaster units on site—ranging from palm-sized objects to human-scale forms—each one a three-dimensional articulation of distilled color, ratio, and reflectivity."]};
return $APP.Hn.i?$APP.Hn.i("p",f):$APP.Hn.call(null,"p",f)}(),function(){var f={className:"mb-6 italic",children:'"We\'re creating material that transforms by its very nature into sculpture—material with a clarity of line and reflection so immediate that the eye can fly across it," says Zadikian.'};return $APP.Gn.i?$APP.Gn.i("p",f):$APP.Gn.call(null,"p",f)}(),function(){var f={className:"mb-6 italic",children:"For Shafrazi, the work's insistence on touch is central: \" It's haptic. Do you know how important that is? That's what makes it. \""};
return $APP.Gn.i?$APP.Gn.i("p",f):$APP.Gn.call(null,"p",f)}(),function(){var f={className:"mb-6",children:"The Pavilion privileges a form of seeing grounded in the body—through weight, temperature, balance, and texture—rather than spectacle or narrative. Units will be cast, stacked, dismantled, and restacked throughout the exhibition, remaining in constant motion."};return $APP.Gn.i?$APP.Gn.i("p",f):$APP.Gn.call(null,"p",f)}(),function(){var f=function(){return{className:"mb-6",children:["By presenting the studio in its raw, working state—without performance or theatrical staging—",
function(){var h={className:"font-bold text-pink-400",children:"THE STUDIO "};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}(),"aligns closely with the Biennale's curatorial framework, ",function(){var h={className:"italic",children:"In Minor Keys"};return $APP.Gn.i?$APP.Gn.i("span",h):$APP.Gn.call(null,"span",h)}(),". The work responds not with commentary or illustration, but with material intelligence, meditative clarity, and poetic restraint—tuning visitors to the lower frequencies: the modest, the elemental, the sanctuary."]}}();
return $APP.Hn.i?$APP.Hn.i("p",f):$APP.Hn.call(null,"p",f)}(),function(){var f={className:"mb-6",children:"The project marks an inner shift for Zadikian, turning away from the bombast of gold toward a quieter thread that has long run through his practice: plaster and pigment. The work foregrounds the rigor, repetition, and material intelligence that have underpinned his oeuvre for decades."};return $APP.Gn.i?$APP.Gn.i("p",f):$APP.Gn.call(null,"p",f)}(),function(){var f={className:"font-bold text-pink-400",
children:"THE STUDIO "};f={children:["In a cultural moment dominated by speed, novelty, and distraction, ",$APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f),"turns toward repetition, exactitude, and touch. Drawing on childhood experiences working with Armenian tuff stone and a lifelong intimacy with plaster, Zadikian produces units that appear plain at first glance, yet reveal unexpected depth through surface, edge, and volume. Together, they form a precise yet open-ended vocabulary—a language of blocks, strata, and intervals that underwrites a larger meditation on resilience, renewal, and the rediscovery of origins."]};
return $APP.Hn.i?$APP.Hn.i("p",f):$APP.Hn.call(null,"p",f)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",e):$APP.Hn.call(null,"div",e)}():null]}}();return $APP.Hn.i?$APP.Hn.i("div",d):$APP.Hn.call(null,"div",d)}(),$APP.lb(b)?function(){var d=function(){return{className:"flex justify-center mt-6 px-4",children:function(){var e=function(){return{"on-click":function(){var f=$APP.lb(b);return c.j?c.j(f):c.call(null,f)},"class":"px-8 py-3",title:"Read full release"}}();return $APP.Gn.i?$APP.Gn.i($APP.Qn,e):
$APP.Gn.call(null,$APP.Qn,e)}()}}();return $APP.Gn.i?$APP.Gn.i("div",d):$APP.Gn.call(null,"div",d)}():null,function(){var d=function(){return{className:"p-4 italic text-lg my-6 mt-12",children:[function(){var e={children:["*Note: As Armenia does not maintain a permanent national pavilion in Venice, the Pavilion must be realized through a rented venue—","a standard and widely accepted model for many non-permanent participating nations. "]};return $APP.Hn.i?$APP.Hn.i("span",e):$APP.Hn.call(null,"span",
e)}(),function(){var e={className:"block mt-4 text-slate-300",children:"The selected site operates at a base rental cost of approximately "};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),function(){var e={className:"font-semibold text-white",children:"€130,000"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),function(){var e={className:"text-slate-300",children:[", representing a strategic and responsible choice when compared to venues in the Giardini or Arsenale, ",
"where base rents—when space is available at all—typically begin at "]};return $APP.Hn.i?$APP.Hn.i("span",e):$APP.Hn.call(null,"span",e)}(),function(){var e={className:"font-semibold text-white",children:"€400,000"};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),function(){var e={className:"text-slate-300",children:", excluding construction, staffing, and operational expenses. "};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),function(){var e={className:"block mt-6",
children:["To support the scale and international significance of this undertaking, ","a dedicated fundraising committee has been formed to guide and advance the project’s philanthropic efforts. "]};return $APP.Hn.i?$APP.Hn.i("span",e):$APP.Hn.call(null,"span",e)}(),function(){var e={className:"block mt-4 text-slate-200",children:"The committee is led by "};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}(),function(){var e={className:"font-medium text-white",children:["Archbishop Hovnan Derderian, Tony Shafrazi, Rafi Ourfalian, Khachik Khudikyan, ",
"Andranik Torosyan, Aram Alajajian, and Vik Hovsepian."]};return $APP.Hn.i?$APP.Hn.i("span",e):$APP.Hn.call(null,"span",e)}(),function(){var e={className:"text-slate-300",children:", ensuring the Pavilion’s successful realization through coordinated leadership, stewardship, and long-term commitment. "};return $APP.Gn.i?$APP.Gn.i("span",e):$APP.Gn.call(null,"span",e)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",d):$APP.Hn.call(null,"div",d)}()]}}();return $APP.Hn.i?$APP.Hn.i(Sw,a):$APP.Hn.call(null,Sw,
a)};
Jw=function(a){$APP.nq(a);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));a=function(){return{idx:4,eyebrow:"VENUE",title:"LOCATION INFORMATION",children:function(){var b=function(){return{className:"space-y-8\n                 ",children:function(){var c=function(){return{className:"text-slate-100 font-medium text-xl",children:[function(){var d=function(){return{className:"p-4 mb-12",children:[function(){var e=function(){return{className:" ",children:["The Armenian Pavilion 2026 unfolds across ",function(){var f=
{className:"font-semibold",children:"three contiguous sites"};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}()," within the historic Arsenale of Venice—",function(){var f={className:"font-semibold",children:"an interior studio"};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}(),", ",function(){var f={className:"font-semibold",children:"an open-air church courtyard"};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}(),", and ",function(){var f={className:"font-semibold",
children:"a canal-side outpost"};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}(),"."]}}();return $APP.Hn.i?$APP.Hn.i("p",e):$APP.Hn.call(null,"p",e)}(),function(){var e=function(){return{className:"mt-4 ",children:["Together, these spaces form a single spatial constellation: ",function(){var f={className:"",children:"a place of work"};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}(),", ",function(){var f={className:"",children:"a place of weather and ruin"};
return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}(),", and ",function(){var f={className:"",children:"a public-facing threshold"};return $APP.Gn.i?$APP.Gn.i("span",f):$APP.Gn.call(null,"span",f)}(),"—each distinct, yet inseparable."]}}();return $APP.Hn.i?$APP.Hn.i("p",e):$APP.Hn.call(null,"p",e)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",d):$APP.Hn.call(null,"div",d)}(),function(){var d=function(){return{className:"text-xl font-medium",children:[function(){var e=function(){return{className:"p-4",
children:[function(){var f={className:"text-3xl pb-4 font-bold uppercase",children:"#1 - TESA 41 (MAIN STUDIO)"};return $APP.Gn.i?$APP.Gn.i("p",f):$APP.Gn.call(null,"p",f)}(),function(){var f=function(){return{className:"space-y-6",children:[function(){var h=function(){return{children:[function(){var k={className:"font-semibold text-slate-100",children:"Tesa 41"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}()," is the primary studio and interior exhibition space for the Armenian Pavilion 2026—",
function(){var k={className:"font-semibold",children:"5,000 square feet"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}()," (",function(){var k={className:"font-semibold",children:"≈465 square meters"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}(),") of expansive industrial volume that functions as the ",function(){var k={className:"italic",children:"operational and conceptual heart"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}()," of the project."]}}();
return $APP.Hn.i?$APP.Hn.i("p",h):$APP.Hn.call(null,"p",h)}(),function(){var h=function(){return{children:["Defined by scale, clarity, and architectural restraint, it is built for sustained ",function(){var k={className:"font-medium",children:"fabrication"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}(),", ",function(){var k={className:"font-medium",children:"assembly"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}(),", and ",function(){var k={className:"font-medium",
children:"reconfiguration"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}()," across the full duration of the Biennale."]}}();return $APP.Hn.i?$APP.Hn.i("p",h):$APP.Hn.call(null,"p",h)}(),function(){var h=function(){return{children:["Here, the Pavilion operates as a ",function(){var k={className:"font-semibold",children:"working studio"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}()," rather than a static exhibition: a place of continuous ",function(){var k=
{className:"font-medium",children:"making"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}(),", ",function(){var k={className:"font-medium",children:"stacking"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}(),", ",function(){var k={className:"font-medium",children:"dismantling"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}(),", and ",function(){var k={className:"font-medium",children:"rebuilding"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,
"span",k)}(),". The interior volume allows the work to expand ",function(){var k={className:"font-medium",children:"horizontally"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}()," and ",function(){var k={className:"font-medium",children:"vertically"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}(),", accommodating both monumental arrangements and intimate moments of material attention."]}}();return $APP.Hn.i?$APP.Hn.i("p",h):$APP.Hn.call(null,"p",h)}(),function(){var h=
function(){return{className:"pt-2",children:[function(){var k={className:"font-semibold text-slate-100",children:"Tesa 41"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}()," anchors the Pavilion physically and philosophically—establishing ",function(){var k={className:"italic",children:"the studio as the artwork itself"};return $APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)}(),"."]}}();return $APP.Hn.i?$APP.Hn.i("p",h):$APP.Hn.call(null,"p",h)}()]}}();return $APP.Hn.i?
$APP.Hn.i("div",f):$APP.Hn.call(null,"div",f)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",e):$APP.Hn.call(null,"div",e)}(),function(){var e=function(){return{className:"w-full h-full flex flex-col gap-4 mt-12",children:[function(){var f=$APP.Dp("outer-ctx"),h=pr(f);$APP.O(h,0,null);h={"playback-id":"KaA1Jf2AusJZ966KPeZrdwJ5S53kboLO4E4fGLrgTLk","should-play?":$APP.O(h,1,null),"allow-audio?":!1};h=$APP.Gn.i?$APP.Gn.i(Gw,h):$APP.Gn.call(null,Gw,h);f={className:"",ref:f,children:h};return $APP.Gn.i?$APP.Gn.i("div",
f):$APP.Gn.call(null,"div",f)}(),function(){var f={"img-src":"https://atd-722658831.imgix.net/tesa_41/weavy-Gemini%203%20(Nano%20Banana%20Pro)-2025-12-22%20at%2011.12.05.tif"};return $APP.Gn.i?$APP.Gn.i($APP.kp,f):$APP.Gn.call(null,$APP.kp,f)}(),function(){var f={"img-src":"https://atd-722658831.imgix.net/tesa_41/weavy-Gemini%203%20(Nano%20Banana%20Pro)-2025-12-22%20at%2010.59.08.tif"};return $APP.Gn.i?$APP.Gn.i($APP.kp,f):$APP.Gn.call(null,$APP.kp,f)}(),function(){var f={"img-src":"https://atd-722658831.imgix.net/tesa_41/weavy-Gemini%203%20(Nano%20Banana%20Pro)-2025-12-22%20at%2010.59.18.tif"};
return $APP.Gn.i?$APP.Gn.i($APP.kp,f):$APP.Gn.call(null,$APP.kp,f)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",e):$APP.Hn.call(null,"div",e)}(),function(){var e=function(){return{className:"mt-12",children:[function(){var f=function(){return{className:"p-4",children:[function(){var h={className:"pb-4 text-3xl font-helvetica font-bold uppercase",children:"#2 - GIARDINO 25 (CHURCH COURTYARD)"};return $APP.Gn.i?$APP.Gn.i("p",h):$APP.Gn.call(null,"p",h)}(),function(){var h=function(){return{className:"space-y-6",
children:[function(){var k=function(){return{children:[function(){var l={className:"font-semibold text-slate-100",children:"Giardino 25"};return $APP.Gn.i?$APP.Gn.i("span",l):$APP.Gn.call(null,"span",l)}()," is an adjacent open-air courtyard formed from the remains of a former church. ","Only the original perimeter walls remain; the roof has long since collapsed—","leaving the space exposed to ",function(){var l={className:"",children:"light"};return $APP.Gn.i?$APP.Gn.i("span",l):$APP.Gn.call(null,
"span",l)}(),", ",function(){var l={className:"",children:"weather"};return $APP.Gn.i?$APP.Gn.i("span",l):$APP.Gn.call(null,"span",l)}(),", and ",function(){var l={className:"",children:"time"};return $APP.Gn.i?$APP.Gn.i("span",l):$APP.Gn.call(null,"span",l)}(),"."]}}();return $APP.Hn.i?$APP.Hn.i("p",k):$APP.Hn.call(null,"p",k)}(),function(){var k={className:"italic",children:"quiet intensity"};k={children:["What survives is a richly textured architectural shell marked by age, erosion, and history. ",
"The courtyard’s stone walls, uneven surfaces, and traces of former sacred use create an atmosphere of ",$APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)," and material depth."]};return $APP.Hn.i?$APP.Hn.i("p",k):$APP.Hn.call(null,"p",k)}(),function(){var k=function(){return{children:["In contrast to the controlled interior of Tesa 41, Giardino 25 functions as a ",function(){var l={className:"font-semibold",children:"threshold space"};return $APP.Gn.i?$APP.Gn.i("span",l):$APP.Gn.call(null,
"span",l)}(),"—neither fully inside nor fully outside—where the work enters into direct dialogue with ",function(){var l={className:"",children:"ruin"};return $APP.Gn.i?$APP.Gn.i("span",l):$APP.Gn.call(null,"span",l)}(),", ",function(){var l={className:"",children:"open sky"};return $APP.Gn.i?$APP.Gn.i("span",l):$APP.Gn.call(null,"span",l)}(),", and ",function(){var l={className:"",children:"changing light"};return $APP.Gn.i?$APP.Gn.i("span",l):$APP.Gn.call(null,"span",l)}(),"."]}}();return $APP.Hn.i?
$APP.Hn.i("p",k):$APP.Hn.call(null,"p",k)}(),function(){var k=function(){return{className:"pt-2",children:[function(){var l={className:"font-semibold text-slate-100",children:"Giardino 25"};return $APP.Gn.i?$APP.Gn.i("span",l):$APP.Gn.call(null,"span",l)}()," extends the Pavilion outward—allowing the project to breathe within an environment shaped as much by ",function(){var l={className:"italic",children:"absence"};return $APP.Gn.i?$APP.Gn.i("span",l):$APP.Gn.call(null,"span",l)}()," as by structure."]}}();
return $APP.Hn.i?$APP.Hn.i("p",k):$APP.Hn.call(null,"p",k)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",h):$APP.Hn.call(null,"div",h)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",f):$APP.Hn.call(null,"div",f)}(),function(){$APP.Zm();var f=$APP.Dp("outer-ctx");var h=pr(f);$APP.O(h,0,null);h={"playback-id":"00r6626C33zSItHxx4iRh1oJPgP1tsH01qR00bNkN7i4go","should-play?":$APP.O(h,1,null),"allow-audio?":!1};h=$APP.Gn.i?$APP.Gn.i(Gw,h):$APP.Gn.call(null,Gw,h);f={className:"",ref:f,children:h};f={className:"w-full h-full flex flex-col gap-4 mt-12",
children:$APP.Gn.i?$APP.Gn.i("div",f):$APP.Gn.call(null,"div",f)};return $APP.Gn.i?$APP.Gn.i("div",f):$APP.Gn.call(null,"div",f)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",e):$APP.Hn.call(null,"div",e)}(),function(){var e=function(){return{className:"mt-12",children:[function(){var f=function(){return{className:"p-4",children:[function(){var h={className:"pb-4 text-3xl font-helvetica font-bold uppercase",children:"#3 — OUTPOST (CANAL WALKWAY)"};return $APP.Gn.i?$APP.Gn.i("p",h):$APP.Gn.call(null,"p",
h)}(),function(){var h=function(){return{className:"space-y-6",children:[function(){var k=function(){return{children:["The ",function(){var l={className:"font-semibold text-slate-100",children:"Outpost"};return $APP.Gn.i?$APP.Gn.i("span",l):$APP.Gn.call(null,"span",l)}()," occupies a brick- and stone-laid walkway that projects into the main canal of the Arsenale. ","Positioned directly in front of ",function(){var l={className:"font-medium",children:"Tesa 41"};return $APP.Gn.i?$APP.Gn.i("span",l):
$APP.Gn.call(null,"span",l)}()," and ",function(){var l={className:"font-medium",children:"Giardino 25"};return $APP.Gn.i?$APP.Gn.i("span",l):$APP.Gn.call(null,"span",l)}(),", this narrow but critical site serves as the Pavilion’s most ",function(){var l={className:"font-semibold",children:"publicly visible point of contact"};return $APP.Gn.i?$APP.Gn.i("span",l):$APP.Gn.call(null,"span",l)}(),"."]}}();return $APP.Hn.i?$APP.Hn.i("p",k):$APP.Hn.call(null,"p",k)}(),function(){var k={className:"italic",
children:"before"};k={children:["The Outpost can be seen from a major pedestrian route leading into the central Arsenale exhibition grounds. ","Visitors cross a well-known, heavily trafficked bridge and encounter this site ",$APP.Gn.i?$APP.Gn.i("span",k):$APP.Gn.call(null,"span",k)," reaching the main Biennale axis."]};return $APP.Hn.i?$APP.Hn.i("p",k):$APP.Hn.call(null,"p",k)}(),function(){var k=function(){return{children:["As a result, the Outpost functions as a ",function(){var l={className:"font-semibold",
children:"signal"};return $APP.Gn.i?$APP.Gn.i("span",l):$APP.Gn.call(null,"span",l)}()," and a ",function(){var l={className:"font-semibold",children:"threshold"};return $APP.Gn.i?$APP.Gn.i("span",l):$APP.Gn.call(null,"span",l)}(),"—an early, unavoidable presence that announces the Pavilion to thousands of passersby, including those who may never enter the interior spaces."]}}();return $APP.Hn.i?$APP.Hn.i("p",k):$APP.Hn.call(null,"p",k)}(),function(){var k={className:"pt-2",children:"This location extends the Pavilion into the daily flow of the Biennale—establishing a continuous visual and conceptual presence along the canal."};
return $APP.Gn.i?$APP.Gn.i("p",k):$APP.Gn.call(null,"p",k)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",h):$APP.Hn.call(null,"div",h)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",f):$APP.Hn.call(null,"div",f)}(),function(){$APP.Zm();var f=$APP.Dp("outer-ctx");var h=pr(f);$APP.O(h,0,null);h={"playback-id":"A602Gnm6A7gpYTl2w4ZnC9xDEnOQQJWbS3dNxhE1O1FE","should-play?":$APP.O(h,1,null),"allow-audio?":!1};h=$APP.Gn.i?$APP.Gn.i(Gw,h):$APP.Gn.call(null,Gw,h);f={className:"",ref:f,children:h};f={className:"w-full h-full flex flex-col gap-4 mt-12",
children:$APP.Gn.i?$APP.Gn.i("div",f):$APP.Gn.call(null,"div",f)};return $APP.Gn.i?$APP.Gn.i("div",f):$APP.Gn.call(null,"div",f)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",e):$APP.Hn.call(null,"div",e)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",d):$APP.Hn.call(null,"div",d)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",c):$APP.Hn.call(null,"div",c)}()}}();return $APP.Gn.i?$APP.Gn.i("div",b):$APP.Gn.call(null,"div",b)}()}}();return $APP.Gn.i?$APP.Gn.i(Sw,a):$APP.Gn.call(null,Sw,a)};
tq=function(a){$APP.nq(a);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));a=function(){return{"section-id":"budget-section",children:[function(){var b={};return $APP.Gn.i?$APP.Gn.i(Ow,b):$APP.Gn.call(null,Ow,b)}(),function(){var b=function(){return{className:"w-full h-full\n               text-white\n               grey-grad\n               flex items-center justify-center flex-col",children:function(){var c=function(){return{className:"flex flex-col w-full lg:w-8/12",children:[function(){var d=
{};return $APP.Gn.i?$APP.Gn.i(qq,d):$APP.Gn.call(null,qq,d)}(),function(){var d={};return $APP.Gn.i?$APP.Gn.i(lr,d):$APP.Gn.call(null,lr,d)}(),function(){var d={};return $APP.Gn.i?$APP.Gn.i(rq,d):$APP.Gn.call(null,rq,d)}(),function(){var d={};return $APP.Gn.i?$APP.Gn.i(pq,d):$APP.Gn.call(null,pq,d)}(),function(){var d={};return $APP.Gn.i?$APP.Gn.i(Jw,d):$APP.Gn.call(null,Jw,d)}(),function(){var d={};return $APP.Gn.i?$APP.Gn.i(sq,d):$APP.Gn.call(null,sq,d)}(),function(){var d={};return $APP.Gn.i?$APP.Gn.i($APP.so,
d):$APP.Gn.call(null,$APP.so,d)}()]}}();return $APP.Hn.i?$APP.Hn.i("div",c):$APP.Hn.call(null,"div",c)}()}}();return $APP.Gn.i?$APP.Gn.i("div",b):$APP.Gn.call(null,"div",b)}()]}}();return $APP.Hn.l?$APP.Hn.l($APP.ao,a,"budget-section"):$APP.Hn.call(null,$APP.ao,a,"budget-section")};
$APP.hr=function(a,b){a=new $APP.U(null,2,5,$APP.X,[$APP.nq(a),b],null);a=$APP.O(a,0,null);a=$APP.S(a);var c=$APP.Gb(a,Uw),d=$APP.Gb(a,Ww),e=$APP.Gb(a,Yw);$APP.w(!1)&&$APP.w()&&((void 0).B?(void 0).B():(void 0).call(null));var f=$APP.Dp("comp-ref");a=$APP.Hp(function(){return $APP.w(c)?d.B?d.B():d.call(null):$APP.sp.gsap.to($APP.A(f),{opacity:0,onComplete:e,duration:1})});b=[c];$APP.yp.i?$APP.yp.i(a,b):$APP.yp.call(null,a,b);a=function(){var h={};h=$APP.Gn.i?$APP.Gn.i(tq,h):$APP.Gn.call(null,tq,h);
return{ref:f,children:h}}();return $APP.Gn.i?$APP.Gn.i("div",a):$APP.Gn.call(null,"div",a)};$APP.Jh.prototype.yd=Xw(0,function(a,b){return new $APP.Jh(this.Bc,$APP.Vb(this.Qb,b),null)});
var Wi=function Wi(a){switch(arguments.length){case 0:return Wi.B();case 1:return Wi.j(arguments[0]);case 2:return Wi.i(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Wi.G(arguments[0],arguments[1],2<c.length?new $APP.cd(c.slice(2),0,null):null)}};Wi.B=function(){return 0};Wi.j=function(a){return a};Wi.i=function(a,b){return a+b};Wi.G=function(a,b,c){return $APP.tb(Wi,a+b,c)};
Wi.V=function(a){var b=$APP.H(a),c=$APP.I(a);a=$APP.H(c);c=$APP.I(c);return this.G(b,a,c)};Wi.sd=2;var Wd=function Wd(a){switch(arguments.length){case 1:return Wd.j(arguments[0]);case 2:return Wd.i(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Wd.G(arguments[0],arguments[1],2<c.length?new $APP.cd(c.slice(2),0,null):null)}};Wd.j=function(a){return a};Wd.i=function(a,b){return a==null?null:Zb(a,b)};
Wd.G=function(a,b,c){for(;;){if(a==null)return null;a=Wd.i(a,b);if($APP.w(c))b=$APP.H(c),c=$APP.I(c);else return a}};Wd.V=function(a){var b=$APP.H(a),c=$APP.I(a);a=$APP.H(c);c=$APP.I(c);return this.G(b,a,c)};Wd.sd=2;
var Lw=new $APP.E(null,"description","description",-1428560544),Yw=new $APP.E(null,"outro-complete-callback","outro-complete-callback",-1973874519),Aw=new $APP.E(null,"amount","amount",364489504),Pw=new $APP.E(null,"on-exit","on-exit",1821961613),Qw=new $APP.E(null,"ar","ar",-2093907980),Nw=new $APP.E(null,"root-margin","root-margin",-1598874814),Iw=new $APP.E(null,"set-expanded-items","set-expanded-items",-112840979),Bw=new $APP.E(null,"cost-data","cost-data",-1991336764),Rw=new $APP.E(null,"eyebrow",
"eyebrow",497521636),Kw=new $APP.E(null,"expanded-items","expanded-items",749320313),Tw=new $APP.E(null,"anchor","anchor",1549638489),Mw=new $APP.E(null,"threshold","threshold",204221583),Ww=new $APP.E(null,"intro-complete-callback","intro-complete-callback",1121849196),Uw=new $APP.E(null,"active","active",1895962068),Dw=new $APP.E(null,"detail","detail",-1545345025),Cw=new $APP.E(null,"details","details",1956795411),Hw=new $APP.E(null,"item","item",249373802);$APP.Xl("budget-view");$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(Fp,"",null,null):(void 0).call(null,Fp,"",null,null)),$APP.oq(Fp,"amp.components.elements.budget-table/total-section"));$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(Ip,"",null,null):(void 0).call(null,Ip,"",null,null)),$APP.oq(Ip,"amp.components.elements.budget-table/detail-line-item"));
$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(Jp,'(hooks/use-ref (str "section-" idx))(use-scroll-to-ref)',null,null):(void 0).call(null,Jp,'(hooks/use-ref (str "section-" idx))(use-scroll-to-ref)',null,null)),$APP.oq(Jp,"amp.components.elements.budget-table/section-line-item"));
$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(Kp,"(hooks/use-state #{})",null,null):(void 0).call(null,Kp,"(hooks/use-state #{})",null,null)),$APP.oq(Kp,"amp.components.elements.budget-table/budget-table"));$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(Ow,'(hooks/use-ref "container-ref")(hooks/use-ref "button-ref")(use-scroll-to-top {:duration 1})(use-scroll-trigger container-ref :start (fn [] (- (win-utils/height) (/ (win-utils/height) 8))) :end "1000000px" :markers? false :debug? false)(use-hover-animations button-ref :over {:opacity 1} :out {:opacity 0.7})(use-toggle-animations {:target container-ref, :on-to {:y 0, :opacity 1}, :off-to {:y -150, :opacity 0.25}, :is-on? is-active?})',
null,null):(void 0).call(null,Ow,'(hooks/use-ref "container-ref")(hooks/use-ref "button-ref")(use-scroll-to-top {:duration 1})(use-scroll-trigger container-ref :start (fn [] (- (win-utils/height) (/ (win-utils/height) 8))) :end "1000000px" :markers? false :debug? false)(use-hover-animations button-ref :over {:opacity 1} :out {:opacity 0.7})(use-toggle-animations {:target container-ref, :on-to {:y 0, :opacity 1}, :off-to {:y -150, :opacity 0.25}, :is-on? is-active?})',null,null)),$APP.oq(Ow,"amp.components.navs.back-up-nav/back-up-nav"));$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(Fw,"",null,null):(void 0).call(null,Fw,"",null,null)),$APP.oq(Fw,"amp.components.elements.aspect-box/aspect-box"));var Gw=$APP.st(new $APP.jt(new $APP.U(null,1,5,$APP.X,["video-background"],null),function(){return $APP.fo})),Lp=new $APP.U(null,9,5,$APP.X,[new $APP.v(null,3,[$APP.$u,"1. Location Cost",Lw,"Secures and operates the Venice exhibition venue: exclusive rental, public-facing staffing, required approvals, insurance coverage, minor architectural adjustments, lighting, and statutory taxes—ensuring the Pavilion is compliant, safe, and fully exhibition-ready.",Cw,new $APP.U(null,12,5,$APP.X,[new $APP.v(null,
2,[$APP.$u,"Base rent",Aw,13E4],null),new $APP.v(null,2,[$APP.$u,"Base staff",Aw,5E4],null),new $APP.v(null,2,[$APP.$u,"Mediator",Aw,25E3],null),new $APP.v(null,2,[$APP.$u,"Cleaning",Aw,7E3],null),new $APP.v(null,2,[$APP.$u,"Utilities",Aw,0],null),new $APP.v(null,2,[$APP.$u,"Permits",Aw,1E4],null),new $APP.v(null,2,[$APP.$u,"Fire cert",Aw,3500],null),new $APP.v(null,2,[$APP.$u,"Liability ins.",Aw,2500],null),new $APP.v(null,2,[$APP.$u,"Build-outs",Aw,9500],null),new $APP.v(null,2,[$APP.$u,"Lighting",
Aw,7500],null),new $APP.v(null,2,[$APP.$u,"Signage tax",Aw,1500],null),new $APP.v(null,2,[$APP.$u,"VAT",Aw,53900],null)],null)],null),new $APP.v(null,3,[$APP.$u,"2. Admin",Lw,"Leadership and project management supporting curatorial direction, artist oversight, coordination, compliance, and travel—keeping the Pavilion contract-ready, fiscally transparent, and operationally stable across the full production timeline.",Cw,new $APP.U(null,16,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Tony (Curator)",Aw,15E3],
null),new $APP.v(null,2,[$APP.$u,"Tina (Curator)",Aw,15E3],null),new $APP.v(null,2,[$APP.$u,"Zadik (Artist)",Aw,15E3],null),new $APP.v(null,2,[$APP.$u,"Aram (Artist)",Aw,15E3],null),new $APP.v(null,2,[$APP.$u,"Admin support",Aw,1E4],null),new $APP.v(null,2,[$APP.$u,"Venice coord.",Aw,22500],null),new $APP.v(null,2,[$APP.$u,"Engineer",Aw,4500],null),new $APP.v(null,2,[$APP.$u,"Legal",Aw,6E3],null),new $APP.v(null,2,[$APP.$u,"Accounting",Aw,9E3],null),new $APP.v(null,2,[$APP.$u,"Bookkeeping",Aw,4800],
null),new $APP.v(null,2,[$APP.$u,"HR/Payroll",Aw,2E3],null),new $APP.v(null,2,[$APP.$u,"Software/tools",Aw,900],null),new $APP.v(null,2,[$APP.$u,"Flights/local",Aw,12E3],null),new $APP.v(null,2,[$APP.$u,"Lodging/per diem",Aw,19500],null),new $APP.v(null,2,[$APP.$u,"Pitch dev",Aw,3500],null),new $APP.v(null,2,[$APP.$u,"Proposal travel",Aw,12500],null)],null)],null),new $APP.v(null,3,[$APP.$u,"3. Production",Lw,"Core fabrication of the work: various artist materials, gilding, casting infrastructure, studio overhead, and skilled labor—supporting precision, durability, and museum-level finish in the sculptural units.",
Cw,new $APP.U(null,13,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Foam core",Aw,17500],null),new $APP.v(null,2,[$APP.$u,"Pigments",Aw,12500],null),new $APP.v(null,2,[$APP.$u,"Plaster",Aw,3750],null),new $APP.v(null,2,[$APP.$u,"Acrylic",Aw,3500],null),new $APP.v(null,2,[$APP.$u,"Gold leaf",Aw,35E3],null),new $APP.v(null,2,[$APP.$u,"Gold sizing",Aw,3530],null),new $APP.v(null,2,[$APP.$u,"Expendables",Aw,2500],null),new $APP.v(null,2,[$APP.$u,"Glass",Aw,3E3],null),new $APP.v(null,2,[$APP.$u,"Studio rent",
Aw,15360],null),new $APP.v(null,2,[$APP.$u,"Utilities/ins.",Aw,7200],null),new $APP.v(null,2,[$APP.$u,"Gilders",Aw,33600],null),new $APP.v(null,2,[$APP.$u,"Casters",Aw,72E3],null),new $APP.v(null,2,[$APP.$u,"Assistants",Aw,24E3],null)],null)],null),new $APP.v(null,3,[$APP.$u,"4. Logistics",Lw,"International and local movement of the work: crating, packing, freight, installation/uninstallation labor, port handling, barge and trucking transfers, storage, and waste removal—ensuring secure handling across Venice’s complex access conditions.",
Cw,new $APP.U(null,20,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Crates",Aw,15E3],null),new $APP.v(null,2,[$APP.$u,"Supplies",Aw,1E4],null),new $APP.v(null,2,[$APP.$u,"Packers",Aw,6E3],null),new $APP.v(null,2,[$APP.$u,"Ship LA–Venice",Aw,3E4],null),new $APP.v(null,2,[$APP.$u,"Ship Venice–LA",Aw,3E4],null),new $APP.v(null,2,[$APP.$u,"Insurance",Aw,12E3],null),new $APP.v(null,2,[$APP.$u,"Installers",Aw,7200],null),new $APP.v(null,2,[$APP.$u,"Uninstallers",Aw,9E3],null),new $APP.v(null,2,[$APP.$u,"Port handling",
Aw,2500],null),new $APP.v(null,2,[$APP.$u,"Barge (inbound)",Aw,3E3],null),new $APP.v(null,2,[$APP.$u,"Truck (inbound)",Aw,1200],null),new $APP.v(null,2,[$APP.$u,"Barge (to site)",Aw,3E3],null),new $APP.v(null,2,[$APP.$u,"Forklift",Aw,1300],null),new $APP.v(null,2,[$APP.$u,"Handling crew",Aw,500],null),new $APP.v(null,2,[$APP.$u,"Short storage",Aw,1200],null),new $APP.v(null,2,[$APP.$u,"Crate storage",Aw,2E3],null),new $APP.v(null,2,[$APP.$u,"Waste removal",Aw,1E3],null),new $APP.v(null,2,[$APP.$u,
"Barge (return)",Aw,3E3],null),new $APP.v(null,2,[$APP.$u,"Truck (return)",Aw,1200],null),new $APP.v(null,2,[$APP.$u,"Port (return)",Aw,2500],null)],null)],null),new $APP.v(null,3,[$APP.$u,"5. Opening Week",Lw,"Opening reception and public-facing diplomatic visibility: hospitality, staffing, security, rentals, technical support, press/VIP coordination, translation, water transport support, and public talks.",Cw,new $APP.U(null,21,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Catering food",Aw,7E3],null),
new $APP.v(null,2,[$APP.$u,"Catering drinks",Aw,2250],null),new $APP.v(null,2,[$APP.$u,"Catering staff",Aw,2500],null),new $APP.v(null,2,[$APP.$u,"Event coord.",Aw,3E3],null),new $APP.v(null,2,[$APP.$u,"Security",Aw,1200],null),new $APP.v(null,2,[$APP.$u,"Rentals",Aw,2500],null),new $APP.v(null,2,[$APP.$u,"A/V \x26 tech",Aw,1500],null),new $APP.v(null,2,[$APP.$u,"Event media",Aw,2500],null),new $APP.v(null,2,[$APP.$u,"Invitations",Aw,1E3],null),new $APP.v(null,2,[$APP.$u,"VIP/press staff",Aw,1500],
null),new $APP.v(null,2,[$APP.$u,"VIP hospitality",Aw,1800],null),new $APP.v(null,2,[$APP.$u,"VIP liaison",Aw,2250],null),new $APP.v(null,2,[$APP.$u,"Protocol",Aw,1E3],null),new $APP.v(null,2,[$APP.$u,"Press packets",Aw,400],null),new $APP.v(null,2,[$APP.$u,"Press A/V",Aw,500],null),new $APP.v(null,2,[$APP.$u,"Interpreter",Aw,700],null),new $APP.v(null,2,[$APP.$u,"Water taxis",Aw,960],null),new $APP.v(null,2,[$APP.$u,"Public talks",Aw,1200],null),new $APP.v(null,2,[$APP.$u,"Talk staff",Aw,800],null),
new $APP.v(null,2,[$APP.$u,"Accessibility",Aw,250],null),new $APP.v(null,2,[$APP.$u,"Program signage",Aw,300],null)],null)],null),new $APP.v(null,3,[$APP.$u,"6. Studio Optrs",Lw,"Seven-month operation of THE STUDIO on-site: staffing, ongoing materials and expendables, local equipment needs, lodging/per diem, and daily maintenance—supporting continuous execution during the Biennale.",Cw,new $APP.U(null,8,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Full-time assistants",Aw,3E4],null),new $APP.v(null,2,[$APP.$u,
"Part-time assistants",Aw,18E3],null),new $APP.v(null,2,[$APP.$u,"Temp staff",Aw,25E3],null),new $APP.v(null,2,[$APP.$u,"Local materials",Aw,5E3],null),new $APP.v(null,2,[$APP.$u,"Expendables",Aw,7E3],null),new $APP.v(null,2,[$APP.$u,"Local equip.",Aw,7500],null),new $APP.v(null,2,[$APP.$u,"Lodging/per diem",Aw,4E4],null),new $APP.v(null,2,[$APP.$u,"Rubbish",Aw,1400],null)],null)],null),new $APP.v(null,3,[$APP.$u,"7. Marketing",Lw,"Visibility and communications campaign: brand system, website, press toolkit, PR writing, advertising, outdoor placements, social media strategy, and media buys—positioning the Pavilion with institutional clarity and global reach.",
Cw,new $APP.U(null,17,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Visual ID",Aw,12500],null),new $APP.v(null,2,[$APP.$u,"Press kit",Aw,7500],null),new $APP.v(null,2,[$APP.$u,"Website",Aw,12E3],null),new $APP.v(null,2,[$APP.$u,"OOH design",Aw,3500],null),new $APP.v(null,2,[$APP.$u,"Exh graphics",Aw,5E3],null),new $APP.v(null,2,[$APP.$u,"Copywriting",Aw,1500],null),new $APP.v(null,2,[$APP.$u,"PR writing",Aw,3500],null),new $APP.v(null,2,[$APP.$u,"Totem OOH",Aw,8400],null),new $APP.v(null,2,[$APP.$u,"Poster print",
Aw,5E3],null),new $APP.v(null,2,[$APP.$u,"City posters",Aw,3E3],null),new $APP.v(null,2,[$APP.$u,"Social ad spend",Aw,5E3],null),new $APP.v(null,2,[$APP.$u,"Campaign mgmt",Aw,5E3],null),new $APP.v(null,2,[$APP.$u,"Digital pub ads",Aw,7500],null),new $APP.v(null,2,[$APP.$u,"Print pub ads",Aw,1E4],null),new $APP.v(null,2,[$APP.$u,"PR pre-open",Aw,1E4],null),new $APP.v(null,2,[$APP.$u,"PR ongoing",Aw,1E4],null),new $APP.v(null,2,[$APP.$u,"Marketing fee",Aw,7500],null)],null)],null),new $APP.v(null,3,
[$APP.$u,"8. Publication",Lw,"Catalogue and printed collateral: commissioned writing, design, editing, printing, and limited-run branded materials—extending the Pavilion into libraries, archives, and institutional discourse.",Cw,new $APP.U(null,14,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Curatorial essay",Aw,2500],null),new $APP.v(null,2,[$APP.$u,"Commissioned essays",Aw,8E3],null),new $APP.v(null,2,[$APP.$u,"Artist texts",Aw,1500],null),new $APP.v(null,2,[$APP.$u,"Wall texts",Aw,1500],null),new $APP.v(null,
2,[$APP.$u,"Catalog design",Aw,1E4],null),new $APP.v(null,2,[$APP.$u,"Edit \x26 layout",Aw,7500],null),new $APP.v(null,2,[$APP.$u,"Catalog print",Aw,24E3],null),new $APP.v(null,2,[$APP.$u,"Catalog misc",Aw,1E3],null),new $APP.v(null,2,[$APP.$u,"Tote design",Aw,3500],null),new $APP.v(null,2,[$APP.$u,"Tote print",Aw,4500],null),new $APP.v(null,2,[$APP.$u,"Tote misc",Aw,500],null),new $APP.v(null,2,[$APP.$u,"Stationery design",Aw,2500],null),new $APP.v(null,2,[$APP.$u,"Stationery print",Aw,1500],null),
new $APP.v(null,2,[$APP.$u,"Stationery misc",Aw,250],null)],null)],null),new $APP.v(null,3,[$APP.$u,"9. Documentation",Lw,"Permanent record of the Pavilion: professional cinematography, sound, photography, editing/color, social deliverables, and archival storage—supporting press, scholarship, donor stewardship, and legacy.",Cw,new $APP.U(null,11,5,$APP.X,[new $APP.v(null,2,[$APP.$u,"Film equip rentals",Aw,1E4],null),new $APP.v(null,2,[$APP.$u,"Film crew",Aw,24900],null),new $APP.v(null,2,[$APP.$u,
"Sound record",Aw,2800],null),new $APP.v(null,2,[$APP.$u,"Install photos",Aw,1750],null),new $APP.v(null,2,[$APP.$u,"Final photos",Aw,1800],null),new $APP.v(null,2,[$APP.$u,"Event photos",Aw,1400],null),new $APP.v(null,2,[$APP.$u,"Edit (assembly)",Aw,3E3],null),new $APP.v(null,2,[$APP.$u,"Edit (final)",Aw,2400],null),new $APP.v(null,2,[$APP.$u,"Sound mix",Aw,1600],null),new $APP.v(null,2,[$APP.$u,"Social clips",Aw,6E3],null),new $APP.v(null,2,[$APP.$u,"Archiving",Aw,750],null)],null)],null)],null);
$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(Sw,"",null,null):(void 0).call(null,Sw,"",null,null)),$APP.oq(Sw,"amp.components.sections.budget-section/section-block"));$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(pq,"",null,null):(void 0).call(null,pq,"",null,null)),$APP.oq(pq,"amp.components.sections.budget-section/cost-breakdown"));
$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(Ew,"(use-scroll-to-id)",null,null):(void 0).call(null,Ew,"(use-scroll-to-id)",null,null)),$APP.oq(Ew,"amp.components.sections.budget-section/section-link"));$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(qq,"",null,null):(void 0).call(null,qq,"",null,null)),$APP.oq(qq,"amp.components.sections.budget-section/header"));
$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(rq,"",null,null):(void 0).call(null,rq,"",null,null)),$APP.oq(rq,"amp.components.sections.budget-section/about"));$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(sq,"",null,null):(void 0).call(null,sq,"",null,null)),$APP.oq(sq,"amp.components.sections.budget-section/non-profit"));
$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(lr,"(hooks/use-state false)",null,null):(void 0).call(null,lr,"(hooks/use-state false)",null,null)),$APP.oq(lr,"amp.components.sections.budget-section/press-release"));
$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(Jw,'(hooks/use-ref "outer-ctx")(use-intersection-observer outer-ctx)(use-touch-enabled)(hooks/use-ref "outer-ctx")(use-intersection-observer outer-ctx)(use-touch-enabled)(hooks/use-ref "outer-ctx")(use-intersection-observer outer-ctx)',null,null):(void 0).call(null,Jw,'(hooks/use-ref "outer-ctx")(use-intersection-observer outer-ctx)(use-touch-enabled)(hooks/use-ref "outer-ctx")(use-intersection-observer outer-ctx)(use-touch-enabled)(hooks/use-ref "outer-ctx")(use-intersection-observer outer-ctx)',
null,null)),$APP.oq(Jw,"amp.components.sections.budget-section/space-section"));$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F(tq,"",null,null):(void 0).call(null,tq,"",null,null)),$APP.oq(tq,"amp.components.sections.budget-section/budget-section"));$APP.w($APP.Ud($APP.Kk,new $APP.v(null,1,[$APP.hn,$APP.Dk],null)))&&($APP.w()&&((void 0).F?(void 0).F($APP.hr,'(hooks/use-ref "comp-ref")(hooks/use-layout-effect [active] (if active (intro-complete-callback) (.to gsap (clojure.core/deref comp-ref) {:opacity 0, :onComplete outro-complete-callback, :duration 1})))',null,null):(void 0).call(null,$APP.hr,'(hooks/use-ref "comp-ref")(hooks/use-layout-effect [active] (if active (intro-complete-callback) (.to gsap (clojure.core/deref comp-ref) {:opacity 0, :onComplete outro-complete-callback, :duration 1})))',
null,null)),$APP.oq($APP.hr,"amp.views.budget-view/budget-view"));$APP.Vl.Yf();
}).call(this);